export default {
  dev: true,
  indent: '  ',
  overrides: true,
  peer: true,
  prod: true,
  resolutions: true,
  semverGroups: [
    {
      range: '~',
      dependencies: ['**'],
      packages: ['@danielheene/*'],
    },
    {
      range: '^',
      dependencies: ['@danielheene/*'],
      packages: ['**'],
    },
  ],
  semverRange: '',
  sortAz: [
    'contributors',
    'maintainers',
    'keywords',
    'dependencies',
    'devDependencies',
    'peerDependencies',
    'optionalDependencies',
    'resolutions',
    'workspaces',
    'scripts',
    'directories',
    'bin',
  ],
  sortFirst: [
    'name',
    'version',
    'license',
    'private',
    'description',
    'keywords',
    'homepage',
    'bugs',
    'repository',
    'author',
    'contributors',
    'maintainers',
    // files
    'sideEffects',
    'type',
    'imports',
    'exports',
    'main',
    'umd:main',
    'jsdelivr',
    'unpkg',
    'module',
    'source',
    'jsnext:main',
    'browser',
    'react-native',
    'types',
    'typesVersions',
    'typings',
    'style',
    'bin',
    'directories',
    'files',
    'workspaces',
    'binary',
  ],
  source: ['package.json', 'web/package.json', 'storybook/package.json', 'packages/*/package.json'],
  versionGroups: [],
} satisfies import('syncpack').RcFile
