node_modules
.next
.turbo
dist
.git
**/*.log
.env*
!.env.example

# Other workspace packages' build output not needed for web's image
storybook/node_modules
storybook/dist
storybook/storybook-static
packages/*/node_modules
packages/*/dist
