import { defineConfig } from 'oxfmt'

/**
 * Oxfmt configuration (replaces Biome's formatter and organizeImports).
 *
 * A `.ts` file rather than `.oxfmtrc.json` so `bun run typecheck` covers it;
 * oxfmt auto-discovers `oxfmt.config.ts`, not `.oxfmtrc.ts`.
 *
 * House style is the Biome one: 100 columns, 2-space indent, single quotes
 * (double in JSX), semicolons only where required, trailing commas everywhere,
 * LF. Biome's `"expand": "always"` has no oxfmt counterpart, so arrays and
 * objects that fit on one line are collapsed unless their first entry already
 * starts on a new line (`objectWrap: 'preserve'`).
 */
export default defineConfig({
  printWidth: 100,
  tabWidth: 2,
  useTabs: false,
  semi: false,
  singleQuote: true,
  jsxSingleQuote: false,
  trailingComma: 'all',
  arrowParens: 'always',
  bracketSpacing: true,
  bracketSameLine: false,
  endOfLine: 'lf',
  objectWrap: 'preserve',

  // Biome's organizeImports groups: builtins, then the frameworks (react,
  // next, payload), other packages, `@/` aliases, relative paths and styles.
  sortImports: {
    customGroups: [
      {
        groupName: 'react',
        elementNamePattern: ['react', 'react/**', 'react-*', 'react-*/**', '@react*/**'],
      },
      {
        groupName: 'next',
        elementNamePattern: ['next', 'next/**', 'next-*', 'next-*/**'],
      },
      {
        groupName: 'payload',
        elementNamePattern: ['@payload-config', 'payload', 'payload/**', 'payload-*'],
      },
      {
        groupName: 'payloadcms',
        elementNamePattern: ['@payloadcms/**'],
      },
    ],
    groups: [
      'builtin',
      'react',
      { newlinesBetween: false },
      'next',
      { newlinesBetween: false },
      'payload',
      { newlinesBetween: false },
      'payloadcms',
      'external',
      'internal',
      ['parent', 'sibling', 'index'],
      'style',
      'unknown',
    ],
    internalPattern: ['@/'],
    // Keeps side-effect imports (CSS, instrumentation) where they are.
    sortSideEffects: false,
  },

  // syncpack owns package.json ordering (`bun run chore:format`).
  sortPackageJson: false,

  ignorePatterns: [
    'node_modules/**',
    '.next/**',
    'out/**',
    'dist/**',
    'coverage/**',
    'storybook-static/**',
    'playwright-report/**',
    'test-results/**',
    'bun.lock',
    'next-env.d.ts',
    // Generated by `bun run generate`.
    'src/types/payload.ts',
    'app/(payload)/admin/importMap.js',
    // Biome never formatted these; keeping them out avoids an unrelated rewrite.
    '**/*.md',
    '**/*.mdx',
    '**/*.yml',
    '**/*.yaml',
    '**/*.html',
    'tsconfig.json',
  ],
})
