import { defineConfig } from 'oxlint'

/**
 * Oxlint configuration (replaces Biome's linter).
 *
 * A `.ts` file rather than `.oxlintrc.json` so `bun run typecheck` covers it;
 * oxlint auto-discovers `oxlint.config.ts`, not `.oxlintrc.ts`, and silently
 * falls back to its defaults when the name is wrong.
 *
 * Mirrors what Biome enforced: its recommended rules for the react, next and
 * types domains, with the same rules switched off or down to warnings.
 */
export default defineConfig({
  plugins: ['eslint', 'typescript', 'unicorn', 'oxc', 'react', 'jsx-a11y', 'nextjs', 'import'],
  categories: {
    correctness: 'error',
  },
  env: {
    browser: true,
    node: true,
    es2024: true,
  },

  ignorePatterns: [
    '.next/**',
    'out/**',
    'dist/**',
    'coverage/**',
    'storybook-static/**',
    'playwright-report/**',
    'test-results/**',
    'next-env.d.ts',
    // Generated by `bun run generate`.
    'src/types/payload.ts',
    'app/(payload)/admin/importMap.js',
  ],

  rules: {
    'typescript/no-explicit-any': 'warn',
    'react/rules-of-hooks': 'error',
    'react/exhaustive-deps': 'warn',
    'react/jsx-key': 'error',
    'react/no-danger-with-children': 'error',
    'react/button-has-type': 'warn',
    'nextjs/no-img-element': 'warn',
    'eslint/no-debugger': 'error',
    'eslint/eqeqeq': [
      'error',
      'always',
      {
        null: 'ignore',
      },
    ],

    // Carried over from biome.json, where these were off or warnings.
    'react/no-array-index-key': 'off',
    'jsx-a11y/aria-role': [
      'warn',
      {
        ignoreNonDOM: true,
        allowedInvalidRoles: ['application', 'draggable'],
      },
    ],
    'jsx-a11y/no-noninteractive-tabindex': 'warn',

    // --- Pre-existing findings, non-blocking like Biome left them -----------
    // Biome reported unused code as warnings and had no equivalent for the
    // rest (React Compiler purity/refs/effect rules, several a11y and unicorn
    // checks). Each still flags code on main, so they warn rather than fail CI
    // and are follow-ups, not part of the migration.
    'eslint/no-unused-vars': [
      'warn',
      {
        args: 'after-used',
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
        ignoreRestSiblings: true,
      },
    ],
    'react/set-state-in-effect': 'warn',
    'react/purity': 'warn',
    'react/refs': 'warn',
    'jsx-a11y/prefer-tag-over-role': 'warn',
    'jsx-a11y/no-noninteractive-element-interactions': 'warn',
    'jsx-a11y/control-has-associated-label': 'warn',
    'jsx-a11y/media-has-caption': 'warn',
    'jsx-a11y/role-supports-aria-props': 'warn',
    'unicorn/no-useless-spread': 'warn',
    'unicorn/no-empty-file': 'warn',
    'eslint/no-unused-expressions': 'warn',
    'eslint/no-control-regex': 'warn',

    // Both are in the correctness category but force full module resolution,
    // the single biggest oxlint slowdown; Biome had no equivalent either.
    'import/default': 'off',
    'import/namespace': 'off',
  },

  overrides: [
    {
      // Storybook render functions are anonymous arrows that legitimately
      // call hooks.
      files: ['**/*.stories.tsx', '.storybook/**'],
      rules: {
        'react/rules-of-hooks': 'off',
      },
    },
    {
      // The root error boundary replaces the whole app, next/link included,
      // so it has to navigate with a plain anchor.
      files: ['app/global-error.tsx'],
      rules: {
        'nextjs/no-html-link-for-pages': 'off',
      },
    },
    {
      files: ['**/*.ts', '**/*.tsx'],
      rules: {
        'eslint/no-undef': 'off',
      },
    },
  ],
})
