import { type Config, PluginUtils } from 'tailwindcss/types/config'
import resolveConfig from 'tailwindcss/resolveConfig'

const config: Config = {
  content: [
    './pages/**/*.{ts,tsx,js,jsx,css}',
    './components/**/*.{ts,tsx,js,jsx,css}',
    './app/**/*.{ts,tsx,js,jsx,css}',
    './src/**/*.{ts,tsx,js,jsx,css}',
  ],
  darkMode: ['selector', '[data-theme="dark"]'],
  plugins: [require('tailwindcss-animate'), require('@tailwindcss/typography')],
  prefix: '',
  safelist: [
    'lg:col-span-4',
    'lg:col-span-6',
    'lg:col-span-8',
    'lg:col-span-12',
    'text-info-900',
    'border-info/75',
    'bg-info/20',
    'text-error-900',
    'border-error/75',
    'bg-error/20',
    'text-success-900',
    'border-success/75',
    'bg-success/20',
    'text-warning-900',
    'border-warning/75',
    'bg-warning/20',
  ],
  theme: {
    container: {
      center: true,
      padding: {
        sm: '1rem',
        DEFAULT: '1rem',
        lg: '2rem',
        md: '2rem',
        xl: '2rem',
        '2xl': '4rem',
      },
      screens: {
        '2xl': '86rem',
        lg: '64rem',
        md: '48rem',
        sm: '40rem',
        xl: '80rem',
      },
    },
    extend: {
      animation: {},
      aspectRatio: {
        '3/2': '3 / 2',
        logo: '2.5 / 1',
      },
      backgroundImage: ({ theme }) => ({
        'gradient-primary': `linear-gradient(to right top, ${theme('colors.blue.600')}, ${theme('colors.violet.600')})`,
      }),
      borderRadius: {
        DEFAULT: 'var(--border-radius)',
        xs: 'var(--border-radius-xs)',
        sm: 'var(--border-radius-sm)',
        md: 'var(--border-radius-md)',
        lg: 'var(--border-radius-lg)',
        xl: 'var(--border-radius-xl)',
        none: 'var(--border-radius-none)',
        full: 'var(--border-radius-full)',
      },
      colors: {
        current: 'var(--color-current)',
        transparent: 'var(--color-transparent)',
        inherit: 'var(--color-inherit)',

        black: 'rgb(var(--color-black) / <alpha-value>)',
        white: 'rgb(var(--color-white) / <alpha-value>)',

        background: 'rgb(var(--color-background) / <alpha-value>)',
        foreground: 'rgb(var(--color-foreground) / <alpha-value>)',

        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        border: 'hsl(var(--border))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        input: 'hsl(var(--input))',
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        ring: 'hsl(var(--ring))',
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },

        primary: {
          DEFAULT: 'rgb(var(--color-primary-500) / <alpha-value>)',
          50: 'rgb(var(--color-primary-50) / <alpha-value>))',
          100: 'rgb(var(--color-primary-100) / <alpha-value>)',
          200: 'rgb(var(--color-primary-200) / <alpha-value>)',
          300: 'rgb(var(--color-primary-300) / <alpha-value>)',
          400: 'rgb(var(--color-primary-400) / <alpha-value>)',
          500: 'rgb(var(--color-primary-500) / <alpha-value>)',
          600: 'rgb(var(--color-primary-600) / <alpha-value>)',
          700: 'rgb(var(--color-primary-700) / <alpha-value>)',
          800: 'rgb(var(--color-primary-800) / <alpha-value>)',
          900: 'rgb(var(--color-primary-900) / <alpha-value>)',
          950: 'rgb(var(--color-primary-950) / <alpha-value>)',
        },
        secondary: {
          DEFAULT: 'rgb(var(--color-secondary-500) / <alpha-value>)',
          50: 'rgb(var(--color-secondary-50) / <alpha-value>)',
          100: 'rgb(var(--color-secondary-100) / <alpha-value>)',
          200: 'rgb(var(--color-secondary-200) / <alpha-value>)',
          300: 'rgb(var(--color-secondary-300) / <alpha-value>)',
          400: 'rgb(var(--color-secondary-400) / <alpha-value>)',
          500: '(rgb(var(--color-secondary-500) / <alpha-value>))',
          600: 'rgb(var(--color-secondary-600) / <alpha-value>)',
          700: 'rgb(var(--color-secondary-700) / <alpha-value>)',
          800: 'rgb(var(--color-secondary-800) / <alpha-value>)',
          900: 'rgb(var(--color-secondary-900) / <alpha-value>)',
          950: 'rgb(var(--color-secondary-950) / <alpha-value>)',
        },
        tertiary: {
          DEFAULT: 'rgb(var(--color-tertiary-500) / <alpha-value>)',
          50: 'rgb(var(--color-tertiary-50) / <alpha-value>)',
          100: 'rgb(var(--color-tertiary-100) / <alpha-value>)',
          200: 'rgb(var(--color-tertiary-200) / <alpha-value>)',
          300: 'rgb(var(--color-tertiary-300) / <alpha-value>)',
          400: 'rgb(var(--color-tertiary-400) / <alpha-value>)',
          500: 'rgb(var(--color-tertiary-500) / <alpha-value>)',
          600: 'rgb(var(--color-tertiary-600) / <alpha-value>)',
          700: 'rgb(var(--color-tertiary-700) / <alpha-value>)',
          800: 'rgb(var(--color-tertiary-800) / <alpha-value>)',
          900: 'rgb(var(--color-tertiary-900) / <alpha-value>)',
          950: 'rgb(var(--color-tertiary-950) / <alpha-value>)',
        },
        info: {
          DEFAULT: 'rgb(var(--color-info-500) / <alpha-value>)',
          50: 'rgb(var(--color-info-50) / <alpha-value>)',
          100: 'rgb(var(--color-info-100) / <alpha-value>)',
          200: 'rgb(var(--color-info-200) / <alpha-value>)',
          300: 'rgb(var(--color-info-300) / <alpha-value>)',
          400: 'rgb(var(--color-info-400) / <alpha-value>)',
          500: 'rgb(var(--color-info-500) / <alpha-value>)',
          600: 'rgb(var(--color-info-600) / <alpha-value>)',
          700: 'rgb(var(--color-info-700) / <alpha-value>)',
          800: 'rgb(var(--color-info-800) / <alpha-value>)',
          900: 'rgb(var(--color-info-900) / <alpha-value>)',
          950: 'rgb(var(--color-info-950) / <alpha-value>)',
        },
        success: {
          DEFAULT: 'rgb(var(--color-success-500) / <alpha-value>)',
          50: 'rgb(var(--color-success-50) / <alpha-value>)',
          100: 'rgb(var(--color-success-100) / <alpha-value>)',
          200: 'rgb(var(--color-success-200) / <alpha-value>)',
          300: 'rgb(var(--color-success-300) / <alpha-value>)',
          400: 'rgb(var(--color-success-400) / <alpha-value>)',
          500: 'rgb(var(--color-success-500) / <alpha-value>)',
          600: 'rgb(var(--color-success-600) / <alpha-value>)',
          700: 'rgb(var(--color-success-700) / <alpha-value>)',
          800: 'rgb(var(--color-success-800) / <alpha-value>)',
          900: 'rgb(var(--color-success-900) / <alpha-value>)',
          950: 'rgb(var(--color-success-950) / <alpha-value>)',
        },
        warning: {
          DEFAULT: 'rgb(var(--color-warning-500) / <alpha-value>)',
          50: 'rgb(var(--color-warning-50) / <alpha-value>)',
          100: 'rgb(var(--color-warning-100) / <alpha-value>)',
          200: 'rgb(var(--color-warning-200) / <alpha-value>)',
          300: 'rgb(var(--color-warning-300) / <alpha-value>)',
          400: 'rgb(var(--color-warning-400) / <alpha-value>)',
          500: 'rgb(var(--color-warning-500) / <alpha-value>)',
          600: 'rgb(var(--color-warning-600) / <alpha-value>)',
          700: 'rgb(var(--color-warning-700) / <alpha-value>)',
          800: 'rgb(var(--color-warning-800) / <alpha-value>)',
          900: 'rgb(var(--color-warning-900) / <alpha-value>)',
          950: 'rgb(var(--color-warning-950) / <alpha-value>)',
        },
        error: {
          DEFAULT: 'rgb(var(--color-error-500) / <alpha-value>)',
          50: 'rgb(var(--color-error-50) / <alpha-value>)',
          100: 'rgb(var(--color-error-100) / <alpha-value>)',
          200: 'rgb(var(--color-error-200) / <alpha-value>)',
          300: 'rgb(var(--color-error-300) / <alpha-value>)',
          400: 'rgb(var(--color-error-400) / <alpha-value>)',
          500: 'rgb(var(--color-error-500) / <alpha-value>)',
          600: 'rgb(var(--color-error-600) / <alpha-value>)',
          700: 'rgb(var(--color-error-700) / <alpha-value>)',
          800: 'rgb(var(--color-error-800) / <alpha-value>)',
          900: 'rgb(var(--color-error-900) / <alpha-value>)',
          950: 'rgb(var(--color-error-950) / <alpha-value>)',
        },
        slate: {
          DEFAULT: 'rgb(var(--color-slate-500) / <alpha-value>)',
          50: 'rgb(var(--color-slate-50) / <alpha-value>)',
          100: 'rgb(var(--color-slate-100) / <alpha-value>)',
          200: 'rgb(var(--color-slate-200) / <alpha-value>)',
          300: 'rgb(var(--color-slate-300) / <alpha-value>)',
          400: 'rgb(var(--color-slate-400) / <alpha-value>)',
          500: 'rgb(var(--color-slate-500) / <alpha-value>)',
          600: 'rgb(var(--color-slate-600) / <alpha-value>)',
          700: 'rgb(var(--color-slate-700) / <alpha-value>)',
          800: 'rgb(var(--color-slate-800) / <alpha-value>)',
          900: 'rgb(var(--color-slate-900) / <alpha-value>)',
          950: 'rgb(var(--color-slate-950) / <alpha-value>)',
        },
        gray: {
          DEFAULT: 'rgb(var(--color-gray-500) / <alpha-value>)',
          50: 'rgb(var(--color-gray-50) / <alpha-value>)',
          100: 'rgb(var(--color-gray-100) / <alpha-value>)',
          200: 'rgb(var(--color-gray-200) / <alpha-value>)',
          300: 'rgb(var(--color-gray-300) / <alpha-value>)',
          400: 'rgb(var(--color-gray-400) / <alpha-value>)',
          500: 'rgb(var(--color-gray-500) / <alpha-value>)',
          600: 'rgb(var(--color-gray-600) / <alpha-value>)',
          700: 'rgb(var(--color-gray-700) / <alpha-value>)',
          800: 'rgb(var(--color-gray-800) / <alpha-value>)',
          900: 'rgb(var(--color-gray-900) / <alpha-value>)',
          950: 'rgb(var(--color-gray-950) / <alpha-value>)',
        },
        zinc: {
          DEFAULT: 'rgb(var(--color-zinc-500) / <alpha-value>)',
          50: 'rgb(var(--color-zinc-50) / <alpha-value>)',
          100: 'rgb(var(--color-zinc-100) / <alpha-value>)',
          200: 'rgb(var(--color-zinc-200) / <alpha-value>)',
          300: 'rgb(var(--color-zinc-300) / <alpha-value>)',
          400: 'rgb(var(--color-zinc-400) / <alpha-value>)',
          500: 'rgb(var(--color-zinc-500) / <alpha-value>)',
          600: 'rgb(var(--color-zinc-600) / <alpha-value>)',
          700: 'rgb(var(--color-zinc-700) / <alpha-value>)',
          800: 'rgb(var(--color-zinc-800) / <alpha-value>)',
          900: 'rgb(var(--color-zinc-900) / <alpha-value>)',
          950: 'rgb(var(--color-zinc-950) / <alpha-value>)',
        },
        neutral: {
          DEFAULT: 'rgb(var(--color-neutral-500) / <alpha-value>)',
          50: 'rgb(var(--color-neutral-50) / <alpha-value>)',
          100: 'rgb(var(--color-neutral-100) / <alpha-value>)',
          200: 'rgb(var(--color-neutral-200) / <alpha-value>)',
          300: 'rgb(var(--color-neutral-300) / <alpha-value>)',
          400: 'rgb(var(--color-neutral-400) / <alpha-value>)',
          500: 'rgb(var(--color-neutral-500) / <alpha-value>)',
          600: 'rgb(var(--color-neutral-600) / <alpha-value>)',
          700: 'rgb(var(--color-neutral-700) / <alpha-value>)',
          800: 'rgb(var(--color-neutral-800) / <alpha-value>)',
          900: 'rgb(var(--color-neutral-900) / <alpha-value>)',
          950: 'rgb(var(--color-neutral-950) / <alpha-value>)',
        },
        stone: {
          DEFAULT: 'rgb(var(--color-stone-500) / <alpha-value>)',
          50: 'rgb(var(--color-stone-50) / <alpha-value>)',
          100: 'rgb(var(--color-stone-100) / <alpha-value>)',
          200: 'rgb(var(--color-stone-200) / <alpha-value>)',
          300: 'rgb(var(--color-stone-300) / <alpha-value>)',
          400: 'rgb(var(--color-stone-400) / <alpha-value>)',
          500: 'rgb(var(--color-stone-500) / <alpha-value>)',
          600: 'rgb(var(--color-stone-600) / <alpha-value>)',
          700: 'rgb(var(--color-stone-700) / <alpha-value>)',
          800: 'rgb(var(--color-stone-800) / <alpha-value>)',
          900: 'rgb(var(--color-stone-900) / <alpha-value>)',
          950: 'rgb(var(--color-stone-950) / <alpha-value>)',
        },
        red: {
          DEFAULT: 'rgb(var(--color-red-500) / <alpha-value>)',
          50: 'rgb(var(--color-red-50) / <alpha-value>)',
          100: 'rgb(var(--color-red-100) / <alpha-value>)',
          200: 'rgb(var(--color-red-200) / <alpha-value>)',
          300: 'rgb(var(--color-red-300) / <alpha-value>)',
          400: 'rgb(var(--color-red-400) / <alpha-value>)',
          500: 'rgb(var(--color-red-500) / <alpha-value>)',
          600: 'rgb(var(--color-red-600) / <alpha-value>)',
          700: 'rgb(var(--color-red-700) / <alpha-value>)',
          800: 'rgb(var(--color-red-800) / <alpha-value>)',
          900: 'rgb(var(--color-red-900) / <alpha-value>)',
          950: 'rgb(var(--color-red-950) / <alpha-value>)',
        },
        orange: {
          50: 'rgb(var(--color-orange-50) / <alpha-value>)',
          100: 'rgb(var(--color-orange-100) / <alpha-value>)',
          200: 'rgb(var(--color-orange-200) / <alpha-value>)',
          300: 'rgb(var(--color-orange-300) / <alpha-value>)',
          400: 'rgb(var(--color-orange-400) / <alpha-value>)',
          500: 'rgb(var(--color-orange-500) / <alpha-value>)',
          600: 'rgb(var(--color-orange-600) / <alpha-value>)',
          700: 'rgb(var(--color-orange-700) / <alpha-value>)',
          800: 'rgb(var(--color-orange-800) / <alpha-value>)',
          900: 'rgb(var(--color-orange-900) / <alpha-value>)',
          950: 'rgb(var(--color-orange-950) / <alpha-value>)',
        },
        amber: {
          DEFAULT: 'rgb(var(--color-amber-500) / <alpha-value>)',
          50: 'rgb(var(--color-amber-50) / <alpha-value>)',
          100: 'rgb(var(--color-amber-100) / <alpha-value>)',
          200: 'rgb(var(--color-amber-200) / <alpha-value>)',
          300: 'rgb(var(--color-amber-300) / <alpha-value>)',
          400: 'rgb(var(--color-amber-400) / <alpha-value>)',
          500: 'rgb(var(--color-amber-500) / <alpha-value>)',
          600: 'rgb(var(--color-amber-600) / <alpha-value>)',
          700: 'rgb(var(--color-amber-700) / <alpha-value>)',
          800: 'rgb(var(--color-amber-800) / <alpha-value>)',
          900: 'rgb(var(--color-amber-900) / <alpha-value>)',
          950: 'rgb(var(--color-amber-950) / <alpha-value>)',
        },
        yellow: {
          DEFAULT: 'rgb(var(--color-yellow-500) / <alpha-value>)',
          50: 'rgb(var(--color-yellow-50) / <alpha-value>)',
          100: 'rgb(var(--color-yellow-100) / <alpha-value>)',
          200: 'rgb(var(--color-yellow-200) / <alpha-value>)',
          300: 'rgb(var(--color-yellow-300) / <alpha-value>)',
          400: 'rgb(var(--color-yellow-400) / <alpha-value>)',
          500: 'rgb(var(--color-yellow-500) / <alpha-value>)',
          600: 'rgb(var(--color-yellow-600) / <alpha-value>)',
          700: 'rgb(var(--color-yellow-700) / <alpha-value>)',
          800: 'rgb(var(--color-yellow-800) / <alpha-value>)',
          900: 'rgb(var(--color-yellow-900) / <alpha-value>)',
          950: 'rgb(var(--color-yellow-950) / <alpha-value>)',
        },
        lime: {
          DEFAULT: 'rgb(var(--color-lime-500) / <alpha-value>)',
          50: 'rgb(var(--color-lime-50) / <alpha-value>)',
          100: 'rgb(var(--color-lime-100) / <alpha-value>)',
          200: 'rgb(var(--color-lime-200) / <alpha-value>)',
          300: 'rgb(var(--color-lime-300) / <alpha-value>)',
          400: 'rgb(var(--color-lime-400) / <alpha-value>)',
          500: 'rgb(var(--color-lime-500) / <alpha-value>)',
          600: 'rgb(var(--color-lime-600) / <alpha-value>)',
          700: 'rgb(var(--color-lime-700) / <alpha-value>)',
          800: 'rgb(var(--color-lime-800) / <alpha-value>)',
          900: 'rgb(var(--color-lime-900) / <alpha-value>)',
          950: 'rgb(var(--color-lime-950) / <alpha-value>)',
        },
        green: {
          DEFAULT: 'rgb(var(--color-green-500) / <alpha-value>)',
          50: 'rgb(var(--color-green-50) / <alpha-value>)',
          100: 'rgb(var(--color-green-100) / <alpha-value>)',
          200: 'rgb(var(--color-green-200) / <alpha-value>)',
          300: 'rgb(var(--color-green-300) / <alpha-value>)',
          400: 'rgb(var(--color-green-400) / <alpha-value>)',
          500: 'rgb(var(--color-green-500) / <alpha-value>)',
          600: 'rgb(var(--color-green-600) / <alpha-value>)',
          700: 'rgb(var(--color-green-700) / <alpha-value>)',
          800: 'rgb(var(--color-green-800) / <alpha-value>)',
          900: 'rgb(var(--color-green-900) / <alpha-value>)',
          950: 'rgb(var(--color-green-950) / <alpha-value>)',
        },
        emerald: {
          DEFAULT: 'rgb(var(--color-emerald-500) / <alpha-value>)',
          50: 'rgb(var(--color-emerald-50) / <alpha-value>)',
          100: 'rgb(var(--color-emerald-100) / <alpha-value>)',
          200: 'rgb(var(--color-emerald-200) / <alpha-value>)',
          300: 'rgb(var(--color-emerald-300) / <alpha-value>)',
          400: 'rgb(var(--color-emerald-400) / <alpha-value>)',
          500: 'rgb(var(--color-emerald-500) / <alpha-value>)',
          600: 'rgb(var(--color-emerald-600) / <alpha-value>)',
          700: 'rgb(var(--color-emerald-700) / <alpha-value>)',
          800: 'rgb(var(--color-emerald-800) / <alpha-value>)',
          900: 'rgb(var(--color-emerald-900) / <alpha-value>)',
          950: 'rgb(var(--color-emerald-950) / <alpha-value>)',
        },
        teal: {
          DEFAULT: 'rgb(var(--color-teal-500) / <alpha-value>)',
          50: 'rgb(var(--color-teal-50) / <alpha-value>)',
          100: 'rgb(var(--color-teal-100) / <alpha-value>)',
          200: 'rgb(var(--color-teal-200) / <alpha-value>)',
          300: 'rgb(var(--color-teal-300) / <alpha-value>)',
          400: 'rgb(var(--color-teal-400) / <alpha-value>)',
          500: 'rgb(var(--color-teal-500) / <alpha-value>)',
          600: 'rgb(var(--color-teal-600) / <alpha-value>)',
          700: 'rgb(var(--color-teal-700) / <alpha-value>)',
          800: 'rgb(var(--color-teal-800) / <alpha-value>)',
          900: 'rgb(var(--color-teal-900) / <alpha-value>)',
          950: 'rgb(var(--color-teal-950) / <alpha-value>)',
        },
        cyan: {
          DEFAULT: 'rgb(var(--color-cyan-500) / <alpha-value>)',
          50: 'rgb(var(--color-cyan-50) / <alpha-value>)',
          100: 'rgb(var(--color-cyan-100) / <alpha-value>)',
          200: 'rgb(var(--color-cyan-200) / <alpha-value>)',
          300: 'rgb(var(--color-cyan-300) / <alpha-value>)',
          400: 'rgb(var(--color-cyan-400) / <alpha-value>)',
          500: 'rgb(var(--color-cyan-500) / <alpha-value>)',
          600: 'rgb(var(--color-cyan-600) / <alpha-value>)',
          700: 'rgb(var(--color-cyan-700) / <alpha-value>)',
          800: 'rgb(var(--color-cyan-800) / <alpha-value>)',
          900: 'rgb(var(--color-cyan-900) / <alpha-value>)',
          950: 'rgb(var(--color-cyan-950) / <alpha-value>)',
        },
        sky: {
          DEFAULT: 'rgb(var(--color-sky-500) / <alpha-value>)',
          50: 'rgb(var(--color-sky-50) / <alpha-value>)',
          100: 'rgb(var(--color-sky-100) / <alpha-value>)',
          200: 'rgb(var(--color-sky-200) / <alpha-value>)',
          300: 'rgb(var(--color-sky-300) / <alpha-value>)',
          400: 'rgb(var(--color-sky-400) / <alpha-value>)',
          500: 'rgb(var(--color-sky-500) / <alpha-value>)',
          600: 'rgb(var(--color-sky-600) / <alpha-value>)',
          700: 'rgb(var(--color-sky-700) / <alpha-value>)',
          800: 'rgb(var(--color-sky-800) / <alpha-value>)',
          900: 'rgb(var(--color-sky-900) / <alpha-value>)',
          950: 'rgb(var(--color-sky-950) / <alpha-value>)',
        },
        blue: {
          DEFAULT: 'rgb(var(--color-blue-500) / <alpha-value>)',
          50: 'rgb(var(--color-blue-50) / <alpha-value>)',
          100: 'rgb(var(--color-blue-100) / <alpha-value>)',
          200: 'rgb(var(--color-blue-200) / <alpha-value>)',
          300: 'rgb(var(--color-blue-300) / <alpha-value>)',
          400: 'rgb(var(--color-blue-400) / <alpha-value>)',
          500: 'rgb(var(--color-blue-500) / <alpha-value>)',
          600: 'rgb(var(--color-blue-600) / <alpha-value>)',
          700: 'rgb(var(--color-blue-700) / <alpha-value>)',
          800: 'rgb(var(--color-blue-800) / <alpha-value>)',
          900: 'rgb(var(--color-blue-900) / <alpha-value>)',
          950: 'rgb(var(--color-blue-950) / <alpha-value>)',
        },
        indigo: {
          DEFAULT: 'rgb(var(--color-indigo-500) / <alpha-value>)',
          50: 'rgb(var(--color-indigo-50) / <alpha-value>)',
          100: 'rgb(var(--color-indigo-100) / <alpha-value>)',
          200: 'rgb(var(--color-indigo-200) / <alpha-value>)',
          300: 'rgb(var(--color-indigo-300) / <alpha-value>)',
          400: 'rgb(var(--color-indigo-400) / <alpha-value>)',
          500: 'rgb(var(--color-indigo-500) / <alpha-value>)',
          600: 'rgb(var(--color-indigo-600) / <alpha-value>)',
          700: 'rgb(var(--color-indigo-700) / <alpha-value>)',
          800: 'rgb(var(--color-indigo-800) / <alpha-value>)',
          900: 'rgb(var(--color-indigo-900) / <alpha-value>)',
          950: 'rgb(var(--color-indigo-950) / <alpha-value>)',
        },
        violet: {
          DEFAULT: 'rgb(var(--color-violet-500) / <alpha-value>)',
          50: 'rgb(var(--color-violet-50) / <alpha-value>)',
          100: 'rgb(var(--color-violet-100) / <alpha-value>)',
          200: 'rgb(var(--color-violet-200) / <alpha-value>)',
          300: 'rgb(var(--color-violet-300) / <alpha-value>)',
          400: 'rgb(var(--color-violet-400) / <alpha-value>)',
          500: 'rgb(var(--color-violet-500) / <alpha-value>)',
          600: 'rgb(var(--color-violet-600) / <alpha-value>)',
          700: 'rgb(var(--color-violet-700) / <alpha-value>)',
          800: 'rgb(var(--color-violet-800) / <alpha-value>)',
          900: 'rgb(var(--color-violet-900) / <alpha-value>)',
          950: 'rgb(var(--color-violet-950) / <alpha-value>)',
        },
        purple: {
          DEFAULT: 'rgb(var(--color-purple-500) / <alpha-value>)',
          50: 'rgb(var(--color-purple-50) / <alpha-value>)',
          100: 'rgb(var(--color-purple-100) / <alpha-value>)',
          200: 'rgb(var(--color-purple-200) / <alpha-value>)',
          300: 'rgb(var(--color-purple-300) / <alpha-value>)',
          400: 'rgb(var(--color-purple-400) / <alpha-value>)',
          500: 'rgb(var(--color-purple-500) / <alpha-value>)',
          600: 'rgb(var(--color-purple-600) / <alpha-value>)',
          700: 'rgb(var(--color-purple-700) / <alpha-value>)',
          800: 'rgb(var(--color-purple-800) / <alpha-value>)',
          900: 'rgb(var(--color-purple-900) / <alpha-value>)',
          950: 'rgb(var(--color-purple-950) / <alpha-value>)',
        },
        fuchsia: {
          DEFAULT: 'rgb(var(--color-fuchsia-500) / <alpha-value>)',
          50: 'rgb(var(--color-fuchsia-50) / <alpha-value>)',
          100: 'rgb(var(--color-fuchsia-100) / <alpha-value>)',
          200: 'rgb(var(--color-fuchsia-200) / <alpha-value>)',
          300: 'rgb(var(--color-fuchsia-300) / <alpha-value>)',
          400: 'rgb(var(--color-fuchsia-400) / <alpha-value>)',
          500: 'rgb(var(--color-fuchsia-500) / <alpha-value>)',
          600: 'rgb(var(--color-fuchsia-600) / <alpha-value>)',
          700: 'rgb(var(--color-fuchsia-700) / <alpha-value>)',
          800: 'rgb(var(--color-fuchsia-800) / <alpha-value>)',
          900: 'rgb(var(--color-fuchsia-900) / <alpha-value>)',
          950: 'rgb(var(--color-fuchsia-950) / <alpha-value>)',
        },
        pink: {
          DEFAULT: 'rgb(var(--color-pink-500) / <alpha-value>)',
          50: 'rgb(var(--color-pink-50) / <alpha-value>)',
          100: 'rgb(var(--color-pink-100) / <alpha-value>)',
          200: 'rgb(var(--color-pink-200) / <alpha-value>)',
          300: 'rgb(var(--color-pink-300) / <alpha-value>)',
          400: 'rgb(var(--color-pink-400) / <alpha-value>)',
          500: 'rgb(var(--color-pink-500) / <alpha-value>)',
          600: 'rgb(var(--color-pink-600) / <alpha-value>)',
          700: 'rgb(var(--color-pink-700) / <alpha-value>)',
          800: 'rgb(var(--color-pink-800) / <alpha-value>)',
          900: 'rgb(var(--color-pink-900) / <alpha-value>)',
          950: 'rgb(var(--color-pink-950) / <alpha-value>)',
        },
        rose: {
          DEFAULT: 'rgb(var(--color-rose-500) / <alpha-value>)',
          50: 'rgb(var(--color-rose-50) / <alpha-value>)',
          100: 'rgb(var(--color-rose-100) / <alpha-value>)',
          200: 'rgb(var(--color-rose-200) / <alpha-value>)',
          300: 'rgb(var(--color-rose-300) / <alpha-value>)',
          400: 'rgb(var(--color-rose-400) / <alpha-value>)',
          500: 'rgb(var(--color-rose-500) / <alpha-value>)',
          600: 'rgb(var(--color-rose-600) / <alpha-value>)',
          700: 'rgb(var(--color-rose-700) / <alpha-value>)',
          800: 'rgb(var(--color-rose-800) / <alpha-value>)',
          900: 'rgb(var(--color-rose-900) / <alpha-value>)',
          950: 'rgb(var(--color-rose-950) / <alpha-value>)',
        },
      },
      fontFamily: {
        mono: ['var(--font-mono)'],
        'jetbrains-mono': ['var(--font-jetbrains-mono)'],
        'pp-supply-mono': ['var(--font-pp-supply-mono)'],
        sans: ['var(--font-sans)'],
        inter: ['var(--font-inter)'],
      },
      keyframes: {},
      spacing: {
        px: '1px',
        0: '0',
        0.5: '0.125rem',
        1: '0.25rem',
        1.5: '0.375rem',
        2: '0.5rem',
        2.5: '0.625rem',
        3: '0.75rem',
        3.5: '0.875rem',
        4: '1rem',
        5: '1.25rem',
        6: '1.5rem',
        7: '1.75rem',
        8: '2rem',
        9: '2.25rem',
        10: '2.5rem',
        11: '2.75rem',
        12: '3rem',
        14: '3.5rem',
        16: '4rem',
        20: '5rem',
        24: '6rem',
        28: '7rem',
        32: '8rem',
        36: '9rem',
        40: '10rem',
        44: '11rem',
        48: '12rem',
        52: '13rem',
        56: '14rem',
        60: '15rem',
        64: '16rem',
        72: '18rem',
        80: '20rem',
        88: '22rem',
        96: '24rem',
        104: '26rem',
        112: '28rem',
        120: '30rem',
        128: '32rem',
        136: '34rem',
        144: '36rem',
        152: '38rem',
        160: '40rem',
        168: '42rem',
      },
      typography: ({ theme }: PluginUtils) => ({
        DEFAULT: {
          css: {
            '--tw-prose-body': theme('colors.foreground'),
            '--tw-prose-bold': theme('colors.inherit'),
            '--tw-prose-bullets': 'rgb(var(--color-primary-500))',
            '--tw-prose-headings': 'rgb(var(--color-primary-500))',
            '--tw-prose-hr': 'rgb(var(--color-primary-500))',
            '--tw-prose-links': theme('colors.inherit'),
            h2: {
              fontFamily: theme('fontFamily.supply-mono'),
              fontSize: '2.3rem',
              fontWeight: 'normal',
              marginBottom: '0.25em',
            },
            h3: {
              fontFamily: theme('fontFamily.supply-mono'),
              fontWeight: 'normal',
              lineHeight: '1.4',
            },
            h4: {
              fontFamily: theme('fontFamily.supply-mono'),
              fontWeight: 'normal',
            },
            h5: {
              fontFamily: theme('fontFamily.supply-mono'),
              fontWeight: 'normal',
            },
            h6: {
              fontFamily: theme('fontFamily.supply-mono'),
              fontWeight: 'normal',
            },
          },
        },
      }),
    },
  },
}

export default config

const resolvedConfig = resolveConfig(config)
export const colors = resolvedConfig.theme.colors
export const screens = resolvedConfig.theme.screens
export const fontSize = resolvedConfig.theme.fontSize
export const fontWeight = resolvedConfig.theme.fontWeight
export const fontFamily = resolvedConfig.theme.fontFamily as Record<string, string>
