/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageLayout".
 */
export type PageLayout = ('default' | 'home' | 'resume' | 'legal') | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SkillType".
 */
export type SkillType =
  | 'programmingLanguages'
  | 'frameworksAndLibraries'
  | 'toolingAndPlatforms'
  | 'testingAndQuality'
  | 'architectureAndPatterns'
  | 'methodologiesAndWorkingPractices';
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LanguageCode".
 */
export type LanguageCode =
  | (
      | 'cs'
      | 'da'
      | 'de'
      | 'en'
      | 'es'
      | 'et'
      | 'fi'
      | 'fr'
      | 'hu'
      | 'ja'
      | 'lv'
      | 'lt'
      | 'no'
      | 'it'
      | 'nl'
      | 'pl'
      | 'pt'
      | 'ro'
      | 'ru'
      | 'sk'
      | 'sl'
      | 'sv'
      | 'uk'
      | 'zh'
    )
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LanguageProficiency".
 */
export type LanguageProficiency = ('a1' | 'a2' | 'b1' | 'b2' | 'c1' | 'c2') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones = 'Europe/Berlin';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    CodeBlock: CodeBlock;
    LinkGroupBlock: LinkGroupBlock;
    OneColumnContentBlock: OneColumnContentBlock;
    TwoColumnContentBlock: TwoColumnContentBlock;
    LegalPublisherBlock: LegalPublisherBlock;
    LegalAuthorshipsBlock: LegalAuthorshipsBlock;
    ResumeAboutMeBlock: ResumeAboutMeBlock;
    ResumeContactBlock: ResumeContactBlock;
    ResumeCustomersBlock: ResumeCustomersBlock;
    ResumeDownloadsBlock: ResumeDownloadsBlock;
    ResumeExperienceBlock: ResumeExperienceBlock;
    ResumeProjectsBlock: ResumeProjectsBlock;
    TrendingBlogPostsBlock: TrendingBlogPostsBlock;
  };
  collections: {
    posts: BlogPostData;
    topics: Topic;
    pages: Page;
    users: User;
    images: MediaImage;
    videos: MediaVideo;
    documents: MediaDocument;
    audios: MediaAudio;
    'resume-customers': ResumeCustomerData;
    'resume-documents': ResumeDocumentData;
    'resume-jobs': ResumeJobData;
    'resume-projects': ResumeProjectData;
    'resume-skills': ResumeSkillData;
    'resume-skill-tags': ResumeSkillTagData;
    'document-references': DocumentReference;
    redirects: Redirect;
    'payload-exports': PayloadExport;
    'payload-imports': PayloadImport;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    topics: {
      relatedPosts: 'posts';
    };
  };
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    images: ImagesSelect<false> | ImagesSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    audios: AudiosSelect<false> | AudiosSelect<true>;
    'resume-customers': ResumeCustomersSelect<false> | ResumeCustomersSelect<true>;
    'resume-documents': ResumeDocumentsSelect<false> | ResumeDocumentsSelect<true>;
    'resume-jobs': ResumeJobsSelect<false> | ResumeJobsSelect<true>;
    'resume-projects': ResumeProjectsSelect<false> | ResumeProjectsSelect<true>;
    'resume-skills': ResumeSkillsSelect<false> | ResumeSkillsSelect<true>;
    'resume-skill-tags': ResumeSkillTagsSelect<false> | ResumeSkillTagsSelect<true>;
    'document-references': DocumentReferencesSelect<false> | DocumentReferencesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-exports': PayloadExportsSelect<false> | PayloadExportsSelect<true>;
    'payload-imports': PayloadImportsSelect<false> | PayloadImportsSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'settings-site': SiteSettings;
    'settings-pdf-builder': PDFGeneratorSettings;
    'settings-global-user': GlobalUserSettings;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'settings-site': SettingsSiteSelect<false> | SettingsSiteSelect<true>;
    'settings-pdf-builder': SettingsPdfBuilderSelect<false> | SettingsPdfBuilderSelect<true>;
    'settings-global-user': SettingsGlobalUserSelect<false> | SettingsGlobalUserSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    'scheduled-resume-generation-widget': ScheduledResumeGenerationWidgetWidget;
    'umami-widget': UmamiWidgetWidget;
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      GenerateDocumentThumbnails: TaskGenerateDocumentThumbnails;
      GenerateVideoThumbnails: TaskGenerateVideoThumbnails;
      CalculateSkillTagInterval: TaskCalculateSkillTagInterval;
      GenerateLocalizedResumeDocument: TaskGenerateLocalizedResumeDocument;
      GenerateResumeFilename: TaskGenerateResumeFilename;
      BuildLocalizedResumeData: TaskBuildLocalizedResumeData;
      GenerateResumeFile: TaskGenerateResumeFile;
      AutoTranslateBilingualField: TaskAutoTranslateBilingualField;
      GenerateResumeDocumentTitle: TaskGenerateResumeDocumentTitle;
      GenerateResumeDocumentSlug: TaskGenerateResumeDocumentSlug;
      CreateResumeDocument: TaskCreateResumeDocument;
      PingUptimeEndpoint: TaskPingUptimeEndpoint;
      SeedCollection: TaskSeedCollection;
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: {
      GenerateResumeDocument: WorkflowGenerateResumeDocument;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'CodeBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkGroupBlock".
 */
export interface LinkGroupBlock {
  links?: {
    entries?:
      | {
          link: LinkFieldData;
          id?: string | null;
        }[]
      | null;
    /**
     * Choose how the links should be aligned.
     */
    alignment?: ('left' | 'right' | 'center' | 'list') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'LinkGroupBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkFieldData".
 */
export interface LinkFieldData {
  reference?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | BlogPostData;
      } | null)
    | ({
        relationTo: 'topics';
        value: string | Topic;
      } | null);
  newTab?: boolean | null;
  url?: string | null;
  iconBefore?: string | null;
  /**
   * Defaults to the title of the linked document. Overwrite it with any text, or mix the two — `{title}` is substituted on render.
   */
  label: string;
  iconAfter?: string | null;
  resolvedLabel?: string | null;
  /**
   * Hides the label visually and uses it as the accessible name instead.
   */
  iconOnly?: boolean | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  protected: boolean;
  slug: string;
  layout?: PageLayout;
  hero?: {
    background?: {
      backgroundType?: ('media' | 'shader') | null;
      /**
       * Fills the first screen. Two or more entries become a cross-fading carousel; a single entry renders on its own.
       */
      media?:
        | (
            | {
                relationTo: 'images';
                value: string | MediaImage;
              }
            | {
                relationTo: 'videos';
                value: string | MediaVideo;
              }
          )[]
        | null;
      shader?: ('darkveil' | 'faulty-terminal' | 'gradient-blinds' | 'grainient') | null;
    };
    contentType?: ('title' | 'custom') | null;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  content?:
    | (
        | CodeBlock
        | LinkGroupBlock
        | OneColumnContentBlock
        | TwoColumnContentBlock
        | LegalPublisherBlock
        | LegalAuthorshipsBlock
        | ResumeAboutMeBlock
        | ResumeContactBlock
        | ResumeCustomersBlock
        | ResumeDownloadsBlock
        | ResumeExperienceBlock
        | ResumeProjectsBlock
        | TrendingBlogPostsBlock
      )[]
    | null;
  /**
   * This field group contains meta information for SEO purposes.
   * It includes fields for title, description, and SERP optimization.
   */
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  generatorFlags?: (
    | 'resume-asset'
    | 'thumbnail'
    | 'document'
    | 'audio-thumbnail'
    | 'video-thumbnail'
    | 'document-thumbnail'
    | 'unsplash-import'
    | 'seeded-dummy'
  )[];
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images".
 */
export interface MediaImage {
  id: string;
  checksum?: string | null;
  alt?: string | null;
  credits?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  blurDataURL?: string | null;
  generatorFlags?: (
    | 'resume-asset'
    | 'thumbnail'
    | 'document'
    | 'audio-thumbnail'
    | 'video-thumbnail'
    | 'document-thumbnail'
    | 'unsplash-import'
    | 'seeded-dummy'
  )[];
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface MediaVideo {
  id: string;
  checksum?: string | null;
  credits?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  thumbnails?:
    | {
        relationTo: 'images';
        value: string | MediaImage;
      }[]
    | null;
  generatorFlags?: (
    | 'resume-asset'
    | 'thumbnail'
    | 'document'
    | 'audio-thumbnail'
    | 'video-thumbnail'
    | 'document-thumbnail'
    | 'unsplash-import'
    | 'seeded-dummy'
  )[];
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OneColumnContentBlock".
 */
export interface OneColumnContentBlock {
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'OneColumnContentBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoColumnContentBlock".
 */
export interface TwoColumnContentBlock {
  contentLeft?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contentRight?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'TwoColumnContentBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LegalPublisherBlock".
 */
export interface LegalPublisherBlock {
  id?: string | null;
  blockName?: string | null;
  blockType: 'LegalPublisherBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LegalAuthorshipsBlock".
 */
export interface LegalAuthorshipsBlock {
  id?: string | null;
  blockName?: string | null;
  blockType: 'LegalAuthorshipsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResumeAboutMeBlock".
 */
export interface ResumeAboutMeBlock {
  /**
   * Shown as the section headline and as its entry in the section navigation. Defaults to the block name when left empty.
   */
  title?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  portrait?: {
    relationTo: 'images';
    value: string | MediaImage;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ResumeAboutMeBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResumeContactBlock".
 */
export interface ResumeContactBlock {
  /**
   * Shown as the section headline and as its entry in the section navigation. Defaults to the block name when left empty.
   */
  title?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ResumeContactBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResumeCustomersBlock".
 */
export interface ResumeCustomersBlock {
  /**
   * Shown as the section headline and as its entry in the section navigation. Defaults to the block name when left empty.
   */
  title?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ResumeCustomersBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResumeDownloadsBlock".
 */
export interface ResumeDownloadsBlock {
  /**
   * Shown as the section headline and as its entry in the section navigation. Defaults to the block name when left empty.
   */
  title?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ResumeDownloadsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResumeExperienceBlock".
 */
export interface ResumeExperienceBlock {
  /**
   * Shown as the section headline and as its entry in the section navigation. Defaults to the block name when left empty.
   */
  title?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ResumeExperienceBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResumeProjectsBlock".
 */
export interface ResumeProjectsBlock {
  /**
   * Shown as the section headline and as its entry in the section navigation. Defaults to the block name when left empty.
   */
  title?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ResumeProjectsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TrendingBlogPostsBlock".
 */
export interface TrendingBlogPostsBlock {
  /**
   * Optional heading shown above the trending blog posts.
   */
  heading?: {
    en?: string | null;
    de?: string | null;
  };
  /**
   * How many trending blog posts to display in this block.
   */
  postCount?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'TrendingBlogPostsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface BlogPostData {
  id: string;
  title: string;
  slug: string;
  hero?: {
    background?: {
      backgroundType?: ('media' | 'shader') | null;
      /**
       * Fills the first screen.
       */
      media?:
        | ({
            relationTo: 'images';
            value: string | MediaImage;
          } | null)
        | ({
            relationTo: 'videos';
            value: string | MediaVideo;
          } | null);
      shader?: ('darkveil' | 'faulty-terminal' | 'gradient-blinds' | 'grainient') | null;
    };
  };
  topics?:
    | {
        relationTo: 'topics';
        value: string | Topic;
      }[]
    | null;
  relatedPosts?:
    | {
        relationTo: 'posts';
        value: string | BlogPostData;
      }[]
    | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * This field group contains meta information for SEO purposes.
   * It includes fields for title, description, and SERP optimization.
   */
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  generatorFlags?: (
    | 'resume-asset'
    | 'thumbnail'
    | 'document'
    | 'audio-thumbnail'
    | 'video-thumbnail'
    | 'document-thumbnail'
    | 'unsplash-import'
    | 'seeded-dummy'
  )[];
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: string;
  _order?: string | null;
  title: string;
  featured?: boolean | null;
  slug: string;
  heroImage?: {
    relationTo: 'images';
    value: string | MediaImage;
  } | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relatedPosts?: {
    docs?: (string | BlogPostData)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * This field group contains meta information for SEO purposes.
   * It includes fields for title, description, and SERP optimization.
   */
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  generatorFlags?: (
    | 'resume-asset'
    | 'thumbnail'
    | 'document'
    | 'audio-thumbnail'
    | 'video-thumbnail'
    | 'document-thumbnail'
    | 'unsplash-import'
    | 'seeded-dummy'
  )[];
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  avatar?: {
    relationTo: 'images';
    value: string | MediaImage;
  } | null;
  /**
   * When enabled, your own visits will be tracked in analytics like any other visitor. Off by default so your admin browsing doesn't skew site statistics.
   */
  enableOwnTracking?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface MediaDocument {
  id: string;
  checksum?: string | null;
  credits?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  thumbnails?:
    | {
        relationTo: 'images';
        value: string | MediaImage;
      }[]
    | null;
  generatorFlags?: (
    | 'resume-asset'
    | 'thumbnail'
    | 'document'
    | 'audio-thumbnail'
    | 'video-thumbnail'
    | 'document-thumbnail'
    | 'unsplash-import'
    | 'seeded-dummy'
  )[];
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audios".
 */
export interface MediaAudio {
  id: string;
  checksum?: string | null;
  credits?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  generatorFlags?: (
    | 'resume-asset'
    | 'thumbnail'
    | 'document'
    | 'audio-thumbnail'
    | 'video-thumbnail'
    | 'document-thumbnail'
    | 'unsplash-import'
    | 'seeded-dummy'
  )[];
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-customers".
 */
export interface ResumeCustomerData {
  id: string;
  _order?: string | null;
  title: string;
  slug: string;
  svg?: string | null;
  generatorFlags?: (
    | 'resume-asset'
    | 'thumbnail'
    | 'document'
    | 'audio-thumbnail'
    | 'video-thumbnail'
    | 'document-thumbnail'
    | 'unsplash-import'
    | 'seeded-dummy'
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-documents".
 */
export interface ResumeDocumentData {
  id: string;
  title: string;
  slug: string;
  createdAt?: string | null;
  jobId?: (string | null) | PayloadJob;
  checksum_en?: string | null;
  checksum_de?: string | null;
  newerVersions?: number | null;
  document_en?: {
    relationTo: 'documents';
    value: string | MediaDocument;
  } | null;
  document_de?: {
    relationTo: 'documents';
    value: string | MediaDocument;
  } | null;
  thumbnails_en?:
    | {
        relationTo: 'images';
        value: string | MediaImage;
      }[]
    | null;
  thumbnails_de?:
    | {
        relationTo: 'images';
        value: string | MediaImage;
      }[]
    | null;
  data_en?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  data_de?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  generatorFlags?: (
    | 'resume-asset'
    | 'thumbnail'
    | 'document'
    | 'audio-thumbnail'
    | 'video-thumbnail'
    | 'document-thumbnail'
    | 'unsplash-import'
    | 'seeded-dummy'
  )[];
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'GenerateDocumentThumbnails'
          | 'GenerateVideoThumbnails'
          | 'CalculateSkillTagInterval'
          | 'GenerateLocalizedResumeDocument'
          | 'GenerateResumeFilename'
          | 'BuildLocalizedResumeData'
          | 'GenerateResumeFile'
          | 'AutoTranslateBilingualField'
          | 'GenerateResumeDocumentTitle'
          | 'GenerateResumeDocumentSlug'
          | 'CreateResumeDocument'
          | 'PingUptimeEndpoint'
          | 'SeedCollection'
          | 'createCollectionExport'
          | 'createCollectionImport'
          | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  workflowSlug?: 'GenerateResumeDocument' | null;
  taskSlug?:
    | (
        | 'inline'
        | 'GenerateDocumentThumbnails'
        | 'GenerateVideoThumbnails'
        | 'CalculateSkillTagInterval'
        | 'GenerateLocalizedResumeDocument'
        | 'GenerateResumeFilename'
        | 'BuildLocalizedResumeData'
        | 'GenerateResumeFile'
        | 'AutoTranslateBilingualField'
        | 'GenerateResumeDocumentTitle'
        | 'GenerateResumeDocumentSlug'
        | 'CreateResumeDocument'
        | 'PingUptimeEndpoint'
        | 'SeedCollection'
        | 'createCollectionExport'
        | 'createCollectionImport'
        | 'schedulePublish'
      )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-jobs".
 */
export interface ResumeJobData {
  id: string;
  employer: string;
  title: string;
  tasks?:
    | {
        task: {
          en: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          de: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
        };
        id?: string | null;
      }[]
    | null;
  startDate: string;
  endDate?: string | null;
  interval?: number | null;
  skillTags?:
    | {
        relationTo: 'resume-skill-tags';
        value: string | ResumeSkillTagData;
      }[]
    | null;
  generatorFlags?: (
    | 'resume-asset'
    | 'thumbnail'
    | 'document'
    | 'audio-thumbnail'
    | 'video-thumbnail'
    | 'document-thumbnail'
    | 'unsplash-import'
    | 'seeded-dummy'
  )[];
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-skill-tags".
 */
export interface ResumeSkillTagData {
  id: string;
  _order?: string | null;
  title: string;
  slug: string;
  interval?: number | null;
  generatorFlags?: (
    | 'resume-asset'
    | 'thumbnail'
    | 'document'
    | 'audio-thumbnail'
    | 'video-thumbnail'
    | 'document-thumbnail'
    | 'unsplash-import'
    | 'seeded-dummy'
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-projects".
 */
export interface ResumeProjectData {
  id: string;
  scope?: string | null;
  title?: string | null;
  images?:
    | {
        relationTo: 'images';
        value: string | MediaImage;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  published?: boolean | null;
  relatedPost?: {
    relationTo: 'posts';
    value: string | BlogPostData;
  } | null;
  generatorFlags?: (
    | 'resume-asset'
    | 'thumbnail'
    | 'document'
    | 'audio-thumbnail'
    | 'video-thumbnail'
    | 'document-thumbnail'
    | 'unsplash-import'
    | 'seeded-dummy'
  )[];
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-skills".
 */
export interface ResumeSkillData {
  id: string;
  content: {
    en: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    de: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  title?: string | null;
  published?: boolean | null;
  type?: SkillType;
  skillTags?:
    | {
        relationTo: 'resume-skill-tags';
        value: string | ResumeSkillTagData;
      }[]
    | null;
  generatorFlags?: (
    | 'resume-asset'
    | 'thumbnail'
    | 'document'
    | 'audio-thumbnail'
    | 'video-thumbnail'
    | 'document-thumbnail'
    | 'unsplash-import'
    | 'seeded-dummy'
  )[];
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-references".
 */
export interface DocumentReference {
  id: string;
  /**
   * Slug of the referenced collection.
   */
  targetCollection: string;
  /**
   * ID of the referenced document.
   */
  targetId: string;
  /**
   * Slug of the collection or global holding the reference.
   */
  sourceCollection: string;
  /**
   * ID of the referencing document (the global slug for globals).
   */
  sourceId: string;
  sourceType: 'collection' | 'global';
  /**
   * Dotted path to the reference within the source document.
   */
  path?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * Path to redirect away from, e.g. /old-article. Leading slash is added automatically; query strings are ignored.
   */
  from: string;
  /**
   * Referencing a document keeps the target correct if its slug changes later.
   */
  type: 'reference' | 'custom';
  toDocument?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | BlogPostData;
      } | null)
    | ({
        relationTo: 'topics';
        value: string | Topic;
      } | null)
    | ({
        relationTo: 'resume-documents';
        value: string | ResumeDocumentData;
      } | null);
  /**
   * An internal path such as /blog, or an absolute URL.
   */
  toPath?: string | null;
  statusCode: '301' | '302' | '307' | '308';
  /**
   * Disable to keep the row without applying it.
   */
  enabled?: boolean | null;
  /**
   * How this redirect was created.
   */
  origin?: ('manual' | 'slug-change') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-exports".
 */
export interface PayloadExport {
  id: string;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-imports".
 */
export interface PayloadImport {
  id: string;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'posts';
        value: string | BlogPostData;
      } | null)
    | ({
        relationTo: 'topics';
        value: string | Topic;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'images';
        value: string | MediaImage;
      } | null)
    | ({
        relationTo: 'videos';
        value: string | MediaVideo;
      } | null)
    | ({
        relationTo: 'documents';
        value: string | MediaDocument;
      } | null)
    | ({
        relationTo: 'audios';
        value: string | MediaAudio;
      } | null)
    | ({
        relationTo: 'resume-customers';
        value: string | ResumeCustomerData;
      } | null)
    | ({
        relationTo: 'resume-documents';
        value: string | ResumeDocumentData;
      } | null)
    | ({
        relationTo: 'resume-jobs';
        value: string | ResumeJobData;
      } | null)
    | ({
        relationTo: 'resume-skill-tags';
        value: string | ResumeSkillTagData;
      } | null)
    | ({
        relationTo: 'document-references';
        value: string | DocumentReference;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hero?:
    | T
    | {
        background?:
          | T
          | {
              backgroundType?: T;
              media?: T;
              shader?: T;
            };
      };
  topics?: T;
  relatedPosts?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  generatorFlags?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  featured?: T;
  slug?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  generatorFlags?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  protected?: T;
  slug?: T;
  layout?: T;
  hero?:
    | T
    | {
        background?:
          | T
          | {
              backgroundType?: T;
              media?: T;
              shader?: T;
            };
        contentType?: T;
        content?: T;
      };
  content?: T | {};
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  generatorFlags?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  enableOwnTracking?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images_select".
 */
export interface ImagesSelect<T extends boolean = true> {
  checksum?: T;
  alt?: T;
  credits?: T;
  blurDataURL?: T;
  generatorFlags?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  checksum?: T;
  credits?: T;
  thumbnails?: T;
  generatorFlags?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  checksum?: T;
  credits?: T;
  thumbnails?: T;
  generatorFlags?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audios_select".
 */
export interface AudiosSelect<T extends boolean = true> {
  checksum?: T;
  credits?: T;
  generatorFlags?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-customers_select".
 */
export interface ResumeCustomersSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  svg?: T;
  generatorFlags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-documents_select".
 */
export interface ResumeDocumentsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  createdAt?: T;
  jobId?: T;
  checksum_en?: T;
  checksum_de?: T;
  newerVersions?: T;
  document_en?: T;
  document_de?: T;
  thumbnails_en?: T;
  thumbnails_de?: T;
  data_en?: T;
  data_de?: T;
  generatorFlags?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-jobs_select".
 */
export interface ResumeJobsSelect<T extends boolean = true> {
  employer?: T;
  title?: T;
  tasks?:
    | T
    | {
        task?:
          | T
          | {
              en?: T;
              de?: T;
            };
        id?: T;
      };
  startDate?: T;
  endDate?: T;
  interval?: T;
  skillTags?: T;
  generatorFlags?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-projects_select".
 */
export interface ResumeProjectsSelect<T extends boolean = true> {
  scope?: T;
  title?: T;
  images?: T;
  description?: T;
  published?: T;
  relatedPost?: T;
  generatorFlags?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-skills_select".
 */
export interface ResumeSkillsSelect<T extends boolean = true> {
  content?:
    | T
    | {
        en?: T;
        de?: T;
      };
  title?: T;
  published?: T;
  type?: T;
  skillTags?: T;
  generatorFlags?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-skill-tags_select".
 */
export interface ResumeSkillTagsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  interval?: T;
  generatorFlags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "document-references_select".
 */
export interface DocumentReferencesSelect<T extends boolean = true> {
  targetCollection?: T;
  targetId?: T;
  sourceCollection?: T;
  sourceId?: T;
  sourceType?: T;
  path?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  type?: T;
  toDocument?: T;
  toPath?: T;
  statusCode?: T;
  enabled?: T;
  origin?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-exports_select".
 */
export interface PayloadExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-imports_select".
 */
export interface PayloadImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  workflowSlug?: T;
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  concurrencyKey?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-site".
 */
export interface SiteSettings {
  id: string;
  general: GeneralSettings;
  header?: HeaderSettings;
  footer?: FooterSettings;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GeneralSettings".
 */
export interface GeneralSettings {
  /**
   * The name of the site.
   */
  siteName?: string | null;
  /**
   * This category is used for generating website metadata.
   */
  category?: string | null;
  /**
   * The host of the site.
   */
  siteHost?: string | null;
  /**
   * The URL of the site.
   */
  siteURL?: string | null;
  /**
   * This template is used for generating the title tag value on each page. Title refers to the actual document title which is suffixed with siteName.
   */
  titleTemplate?: string | null;
  /**
   * This description is used for generating website metadata.  This description is also used as fallback if no document description is available.
   */
  description?: string | null;
  image?: {
    relationTo: 'images';
    value: string | MediaImage;
  } | null;
  errorHero?:
    | (
        | {
            relationTo: 'videos';
            value: string | MediaVideo;
          }
        | {
            relationTo: 'images';
            value: string | MediaImage;
          }
      )[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeaderSettings".
 */
export interface HeaderSettings {
  mainNavigation?: {
    entries?:
      | {
          link: LinkFieldData;
          id?: string | null;
        }[]
      | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterSettings".
 */
export interface FooterSettings {
  column1?: {
    isActive?: boolean | null;
    title?: string | null;
    entries?:
      | {
          link: LinkFieldData;
          id?: string | null;
        }[]
      | null;
  };
  column2?: {
    isActive?: boolean | null;
    title?: string | null;
    entries?:
      | {
          link: LinkFieldData;
          id?: string | null;
        }[]
      | null;
  };
  column3?: {
    isActive?: boolean | null;
    title?: string | null;
    entries?:
      | {
          link: LinkFieldData;
          id?: string | null;
        }[]
      | null;
  };
  legalPages?: {
    entries?:
      | {
          link: LinkFieldData;
          id?: string | null;
        }[]
      | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-pdf-builder".
 */
export interface PDFGeneratorSettings {
  id: string;
  /**
   * The document name template for the documents collection.  
   * The document contains all meta data, file references and the data which was used to generate the PDFs.
   */
  documentTitleTemplate?: string | null;
  /**
   * The filename template for the generated PDF which must satisfy both locales and result in two different filenames.  
   * To get an full overview of all available variables or filter functions use the info icon.
   */
  filenameTemplate?: string | null;
  generateThrottle?: number | null;
  timeoutBetweenJobs?: number | null;
  maximumRetries?: number | null;
  skillSorting?: SkillSorting;
  updatedAt?: string | null;
  createdAt?: string | null;
}
export interface SkillSorting {
  skillTypeSortable: SkillTypeSortable[];
  programmingLanguages: SkillEntrySortable[];
  frameworksAndLibraries: SkillEntrySortable[];
  toolingAndPlatforms: SkillEntrySortable[];
  testingAndQuality: SkillEntrySortable[];
  architectureAndPatterns: SkillEntrySortable[];
  methodologiesAndWorkingPractices: SkillEntrySortable[];
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SkillTypeSortable".
 */
export interface SkillTypeSortable {
  id: SkillType;
  label: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SkillEntrySortable".
 */
export interface SkillEntrySortable {
  id: string;
  label: string;
  caption?: string;
}
/**
 * These user details are stored centrally and used throughout the website wherever the user's profile information is needed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-global-user".
 */
export interface GlobalUserSettings {
  id: string;
  /**
   * Upload your profile picture here.<br />
   * You can choose between a regular and a duotone version.
   */
  portrait?: {
    regular?: {
      relationTo: 'images';
      value: string | MediaImage;
    } | null;
    duotone?: {
      relationTo: 'images';
      value: string | MediaImage;
    } | null;
  };
  url?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  name?: string | null;
  gender?: string | null;
  pronouns?: string | null;
  jobTitle?: string | null;
  homeLocation?: string | null;
  birthPlace?: string | null;
  birthDate?: string | null;
  languages?:
    | {
        language?: LanguageCode;
        proficiency?: LanguageProficiency;
        id?: string | null;
      }[]
    | null;
  taxID?: string | null;
  vatID?: string | null;
  duns?: string | null;
  telephone?: string | null;
  email?: string | null;
  /**
   * This section describes your address information.
   * Those informations are also used on the legal-notice page.
   */
  address?: {
    en?: AddressData;
    de?: AddressData;
  };
  /**
   * This section describes links to your profiles on other platforms, such as social media accounts or personal websites.
   * Those links are also used in the footer of the website in the same order.
   */
  sameAs?:
    | {
        icon?: string | null;
        name?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * This section describes the organization you work for.
   * It can be used to generate structured data about your employment.
   */
  worksFor?: {
    name?: string | null;
    url?: string | null;
    address?: {
      en?: AddressData;
      de?: AddressData;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AddressData".
 */
export interface AddressData {
  street?: string | null;
  number?: string | null;
  postCode?: string | null;
  place?: string | null;
  countryCode?: string | null;
  countryName?: string | null;
  region?: string | null;
  locality?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  location?: [number, number] | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: string;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-site_select".
 */
export interface SettingsSiteSelect<T extends boolean = true> {
  general?: T | GeneralSettingsSelect<T>;
  header?: T | HeaderSettingsSelect<T>;
  footer?: T | FooterSettingsSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GeneralSettings_select".
 */
export interface GeneralSettingsSelect<T extends boolean = true> {
  siteName?: T;
  category?: T;
  siteHost?: T;
  siteURL?: T;
  titleTemplate?: T;
  description?: T;
  image?: T;
  errorHero?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeaderSettings_select".
 */
export interface HeaderSettingsSelect<T extends boolean = true> {
  mainNavigation?:
    | T
    | {
        entries?:
          | T
          | {
              link?: T | LinkFieldDataSelect<T>;
              id?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkFieldData_select".
 */
export interface LinkFieldDataSelect<T extends boolean = true> {
  reference?: T;
  newTab?: T;
  url?: T;
  iconBefore?: T;
  label?: T;
  iconAfter?: T;
  resolvedLabel?: T;
  iconOnly?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterSettings_select".
 */
export interface FooterSettingsSelect<T extends boolean = true> {
  column1?:
    | T
    | {
        isActive?: T;
        title?: T;
        entries?:
          | T
          | {
              link?: T | LinkFieldDataSelect<T>;
              id?: T;
            };
      };
  column2?:
    | T
    | {
        isActive?: T;
        title?: T;
        entries?:
          | T
          | {
              link?: T | LinkFieldDataSelect<T>;
              id?: T;
            };
      };
  column3?:
    | T
    | {
        isActive?: T;
        title?: T;
        entries?:
          | T
          | {
              link?: T | LinkFieldDataSelect<T>;
              id?: T;
            };
      };
  legalPages?:
    | T
    | {
        entries?:
          | T
          | {
              link?: T | LinkFieldDataSelect<T>;
              id?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-pdf-builder_select".
 */
export interface SettingsPdfBuilderSelect<T extends boolean = true> {
  documentTitleTemplate?: T;
  filenameTemplate?: T;
  generateThrottle?: T;
  timeoutBetweenJobs?: T;
  maximumRetries?: T;
  skillSorting?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-global-user_select".
 */
export interface SettingsGlobalUserSelect<T extends boolean = true> {
  portrait?:
    | T
    | {
        regular?: T;
        duotone?: T;
      };
  url?: T;
  firstName?: T;
  lastName?: T;
  name?: T;
  gender?: T;
  pronouns?: T;
  jobTitle?: T;
  homeLocation?: T;
  birthPlace?: T;
  birthDate?: T;
  languages?:
    | T
    | {
        language?: T;
        proficiency?: T;
        id?: T;
      };
  taxID?: T;
  vatID?: T;
  duns?: T;
  telephone?: T;
  email?: T;
  address?:
    | T
    | {
        en?: T | AddressDataSelect<T>;
        de?: T | AddressDataSelect<T>;
      };
  sameAs?:
    | T
    | {
        icon?: T;
        name?: T;
        url?: T;
        id?: T;
      };
  worksFor?:
    | T
    | {
        name?: T;
        url?: T;
        address?:
          | T
          | {
              en?: T | AddressDataSelect<T>;
              de?: T | AddressDataSelect<T>;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AddressData_select".
 */
export interface AddressDataSelect<T extends boolean = true> {
  street?: T;
  number?: T;
  postCode?: T;
  place?: T;
  countryCode?: T;
  countryName?: T;
  region?: T;
  locality?: T;
  location?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scheduled-resume-generation-widget_widget".
 */
export interface ScheduledResumeGenerationWidgetWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "umami-widget_widget".
 */
export interface UmamiWidgetWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerateDocumentThumbnails".
 */
export interface TaskGenerateDocumentThumbnails {
  input: {
    documentId: string;
    maxThumbnails?: number | null;
  };
  output: {
    thumbnailIDs?: string[] | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerateVideoThumbnails".
 */
export interface TaskGenerateVideoThumbnails {
  input: {
    videoId: string;
    timestampInSeconds?: number | null;
  };
  output: {
    thumbnailIDs?: string[] | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCalculateSkillTagInterval".
 */
export interface TaskCalculateSkillTagInterval {
  input: {
    skillTagId: string;
  };
  output: {
    interval?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerateLocalizedResumeDocument".
 */
export interface TaskGenerateLocalizedResumeDocument {
  input: {
    locale: 'en' | 'de';
    sharedId: string;
    filenameTemplate: string;
    createdAt: string;
    documentSlug: string;
  };
  output: {
    resumeFileId: string;
    resumeFileChecksum: string;
    resumeThumbnailIds: string[];
    resumeDocumentData:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerateResumeFilename".
 */
export interface TaskGenerateResumeFilename {
  input: {
    filenameTemplate: string;
    sharedId: string;
    locale: 'en' | 'de';
  };
  output: {
    filename: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskBuildLocalizedResumeData".
 */
export interface TaskBuildLocalizedResumeData {
  input: {
    locale: 'en' | 'de';
    filename: string;
    createdAt: string;
    documentSlug: string;
  };
  output: {
    resumeDocumentData:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerateResumeFile".
 */
export interface TaskGenerateResumeFile {
  input: {
    filename: string;
    createdAt: string;
    resumeDocumentData:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    locale: string;
  };
  output: {
    resumeFileId: string;
    resumeFileChecksum: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskAutoTranslateBilingualField".
 */
export interface TaskAutoTranslateBilingualField {
  input: {
    mode: string;
    collectionSlug: string;
    docId?: string | null;
    path: string;
    sourceLanguage: string;
    targetLanguage: string;
    sourceValue:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerateResumeDocumentTitle".
 */
export interface TaskGenerateResumeDocumentTitle {
  input: {
    documentTitleTemplate: string;
    sharedId: string;
  };
  output: {
    documentTitle: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerateResumeDocumentSlug".
 */
export interface TaskGenerateResumeDocumentSlug {
  input: {
    documentTitle: string;
  };
  output: {
    documentSlug: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateResumeDocument".
 */
export interface TaskCreateResumeDocument {
  input: {
    documentTitle: string;
    documentSlug: string;
    createdAt: string;
    jobId: string;
    resumeFileIdEn: string;
    resumeFileChecksumEn: string;
    resumeThumbnailIdsEn: string[];
    resumeDocumentDataEn:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    resumeFileIdDe: string;
    resumeFileChecksumDe: string;
    resumeThumbnailIdsDe: string[];
    resumeDocumentDataDe:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output: {
    success: boolean;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskPingUptimeEndpoint".
 */
export interface TaskPingUptimeEndpoint {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSeedCollection".
 */
export interface TaskSeedCollection {
  input: {
    collection: string;
    mode: string;
    count?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | 'posts'
      | 'topics'
      | 'pages'
      | 'users'
      | 'images'
      | 'videos'
      | 'documents'
      | 'audios'
      | 'resume-customers'
      | 'resume-documents'
      | 'resume-jobs'
      | 'resume-projects'
      | 'resume-skills'
      | 'resume-skill-tags'
      | 'document-references'
      | 'redirects'
      | 'payload-exports'
      | 'payload-imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'posts';
          value: string | BlogPostData;
        } | null)
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowGenerateResumeDocument".
 */
export interface WorkflowGenerateResumeDocument {
  input: {
    documentTitleTemplate: string;
    filenameTemplate: string;
    sharedId: string;
    maximumRetries: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}