/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconFieldValue".
 */
export type IconFieldValue =
  | (
      | 'archlinux'
      | 'cloudflare'
      | 'cloudflare-pages'
      | 'cloudflare-workers'
      | 'debian'
      | 'docker'
      | 'figma'
      | 'github'
      | 'github-actions'
      | 'github-pages'
      | 'gitlab'
      | 'goland'
      | 'home-assistant'
      | 'intellij'
      | 'javascript'
      | 'jetbrains'
      | 'kubernetes'
      | 'linkedin'
      | 'linux'
      | 'mail'
      | 'phone'
      | 'namecheap'
      | 'next-js'
      | 'node-js'
      | 'one-password'
      | 'payload'
      | 'phpstorm'
      | 'pycharm'
      | 'rancher'
      | 'react'
      | 'rust'
      | 'sanity'
      | 'storybook'
      | 'synology'
      | 'tailscale'
      | 'ubuntu'
      | 'unsplash'
      | 'vercel'
      | 'webstorm'
      | 'whatsapp'
      | 'wireguard'
      | 'xing'
      | 'zigbee'
    )
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageLayout".
 */
export type PageLayout = ('default' | 'home' | 'resume' | 'legal') | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SkillType".
 */
export type SkillType =
  | 'programmingLanguages'
  | 'frameworksAndLibraries'
  | 'toolingAndPlatforms'
  | 'testingAndQuality'
  | 'architectureAndPatterns'
  | 'methodologiesAndWorkingPractices';
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LanguageCode".
 */
export type LanguageCode =
  | (
      | 'cs'
      | 'da'
      | 'de'
      | 'en'
      | 'es'
      | 'et'
      | 'fi'
      | 'fr'
      | 'hu'
      | 'ja'
      | 'lv'
      | 'lt'
      | 'no'
      | 'it'
      | 'nl'
      | 'pl'
      | 'pt'
      | 'ro'
      | 'ru'
      | 'sk'
      | 'sl'
      | 'sv'
      | 'uk'
      | 'zh'
    )
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LanguageProficiency".
 */
export type LanguageProficiency = ('a1' | 'a2' | 'b1' | 'b2' | 'c1' | 'c2') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones = 'Europe/Berlin';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    CodeBlock: CodeBlock;
    LinkGroupBlock: LinkGroupBlock;
    OneColumnContentBlock: OneColumnContentBlock;
    TwoColumnContentBlock: TwoColumnContentBlock;
    ResumeAboutMeBlock: ResumeAboutMeBlock;
    ResumeContactBlock: ResumeContactBlock;
    ResumeCustomersBlock: ResumeCustomersBlock;
    ResumeDownloadsBlock: ResumeDownloadsBlock;
    ResumeExperienceBlock: ResumeExperienceBlock;
    ResumeProjectsBlock: ResumeProjectsBlock;
  };
  collections: {
    posts: BlogPostData;
    topics: Topic;
    pages: Page;
    users: User;
    images: MediaImage;
    videos: MediaVideo;
    documents: MediaDocument;
    audios: MediaAudio;
    'resume-customers': ResumeCustomerData;
    'resume-documents': ResumeDocumentData;
    'resume-files': ResumeFileData;
    'resume-jobs': ResumeJobData;
    'resume-projects': ResumeProjectData;
    'resume-skills': ResumeSkillData;
    'resume-skill-tags': ResumeSkillTagData;
    'payload-exports': PayloadExport;
    'payload-imports': PayloadImport;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
    'payload-query-presets': PayloadQueryPreset;
  };
  collectionsJoins: {
    topics: {
      relatedPosts: 'posts';
    };
  };
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    images: ImagesSelect<false> | ImagesSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    audios: AudiosSelect<false> | AudiosSelect<true>;
    'resume-customers': ResumeCustomersSelect<false> | ResumeCustomersSelect<true>;
    'resume-documents': ResumeDocumentsSelect<false> | ResumeDocumentsSelect<true>;
    'resume-files': ResumeFilesSelect<false> | ResumeFilesSelect<true>;
    'resume-jobs': ResumeJobsSelect<false> | ResumeJobsSelect<true>;
    'resume-projects': ResumeProjectsSelect<false> | ResumeProjectsSelect<true>;
    'resume-skills': ResumeSkillsSelect<false> | ResumeSkillsSelect<true>;
    'resume-skill-tags': ResumeSkillTagsSelect<false> | ResumeSkillTagsSelect<true>;
    'payload-exports': PayloadExportsSelect<false> | PayloadExportsSelect<true>;
    'payload-imports': PayloadImportsSelect<false> | PayloadImportsSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
    'payload-query-presets': PayloadQueryPresetsSelect<false> | PayloadQueryPresetsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'settings-site': SiteSettings;
    'settings-pdf-builder': PDFGeneratorSettings;
    'settings-global-user': GlobalUserSettings;
  };
  globalsSelect: {
    'settings-site': SettingsSiteSelect<false> | SettingsSiteSelect<true>;
    'settings-pdf-builder': SettingsPdfBuilderSelect<false> | SettingsPdfBuilderSelect<true>;
    'settings-global-user': SettingsGlobalUserSelect<false> | SettingsGlobalUserSelect<true>;
  };
  locale: null;
  widgets: {
    'umami-widget': UmamiWidgetWidget;
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      GenerateDocumentThumbnails: TaskGenerateDocumentThumbnails;
      CalculateSkillTagInterval: TaskCalculateSkillTagInterval;
      GenerateLocalizedResumeDocument: TaskGenerateLocalizedResumeDocument;
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: {
      GenerateResumeDocument: WorkflowGenerateResumeDocument;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'CodeBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkGroupBlock".
 */
export interface LinkGroupBlock {
  links?: {
    entries?:
      | {
          link: LinkFieldData;
          id?: string | null;
        }[]
      | null;
    /**
     * Choose how the links should be aligned.
     */
    alignment?: ('left' | 'right' | 'center' | 'list') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'LinkGroupBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkFieldData".
 */
export interface LinkFieldData {
  type?: ('reference' | 'custom') | null;
  newTab?: boolean | null;
  icon?: IconFieldValue;
  label: string;
  iconOnly?: boolean | null;
  reference?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | BlogPostData;
      } | null)
    | ({
        relationTo: 'topics';
        value: string | Topic;
      } | null);
  url?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  protected: boolean;
  slug: string;
  layout?: PageLayout;
  hero?: {
    media?:
      | {
          relationTo: 'images';
          value: string | MediaImage;
        }[]
      | null;
    contentType?: ('title' | 'custom') | null;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  content?:
    | (
        | CodeBlock
        | LinkGroupBlock
        | OneColumnContentBlock
        | TwoColumnContentBlock
        | ResumeAboutMeBlock
        | ResumeContactBlock
        | ResumeCustomersBlock
        | ResumeDownloadsBlock
        | ResumeExperienceBlock
        | ResumeProjectsBlock
      )[]
    | null;
  /**
   * This field group contains meta information for SEO purposes.
   * It includes fields for title, description, and SERP optimization.
   */
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images".
 */
export interface MediaImage {
  id: string;
  checksum?: string | null;
  alt?: string | null;
  credits?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  blurDataURL?: string | null;
  generatorFlags?: (
    | '+auto-generated'
    | '-auto-generated'
    | '+resume-asset'
    | '-resume-asset'
    | '+thumbnail'
    | '-thumbnail'
    | '+document'
    | '-document'
    | '+audio-thumbnail'
    | '-audio-thumbnail'
    | '+video-thumbnail'
    | '-video-thumbnail'
    | '+document-thumbnail'
    | '-document-thumbnail'
  )[];
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OneColumnContentBlock".
 */
export interface OneColumnContentBlock {
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'OneColumnContentBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoColumnContentBlock".
 */
export interface TwoColumnContentBlock {
  contentLeft?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contentRight?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'TwoColumnContentBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResumeAboutMeBlock".
 */
export interface ResumeAboutMeBlock {
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  portrait?: {
    relationTo: 'images';
    value: string | MediaImage;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ResumeAboutMeBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResumeContactBlock".
 */
export interface ResumeContactBlock {
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ResumeContactBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResumeCustomersBlock".
 */
export interface ResumeCustomersBlock {
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ResumeCustomersBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResumeDownloadsBlock".
 */
export interface ResumeDownloadsBlock {
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ResumeDownloadsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResumeExperienceBlock".
 */
export interface ResumeExperienceBlock {
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ResumeExperienceBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResumeProjectsBlock".
 */
export interface ResumeProjectsBlock {
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ResumeProjectsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface BlogPostData {
  id: string;
  title: string;
  slug: string;
  heroImage?: {
    relationTo: 'images';
    value: string | MediaImage;
  } | null;
  topics?:
    | {
        relationTo: 'topics';
        value: string | Topic;
      }[]
    | null;
  relatedPosts?:
    | {
        relationTo: 'posts';
        value: string | BlogPostData;
      }[]
    | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * This field group contains meta information for SEO purposes.
   * It includes fields for title, description, and SERP optimization.
   */
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: string;
  _order?: string | null;
  title: string;
  featured?: boolean | null;
  slug: string;
  heroImage?: {
    relationTo: 'images';
    value: string | MediaImage;
  } | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  relatedPosts?: {
    docs?: (string | BlogPostData)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * This field group contains meta information for SEO purposes.
   * It includes fields for title, description, and SERP optimization.
   */
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  avatar?: {
    relationTo: 'images';
    value: string | MediaImage;
  } | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface MediaVideo {
  id: string;
  checksum?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  thumbnails?:
    | {
        relationTo: 'images';
        value: string | MediaImage;
      }[]
    | null;
  generatorFlags?: (
    | '+auto-generated'
    | '-auto-generated'
    | '+resume-asset'
    | '-resume-asset'
    | '+thumbnail'
    | '-thumbnail'
    | '+document'
    | '-document'
    | '+audio-thumbnail'
    | '-audio-thumbnail'
    | '+video-thumbnail'
    | '-video-thumbnail'
    | '+document-thumbnail'
    | '-document-thumbnail'
  )[];
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface MediaDocument {
  id: string;
  checksum?: string | null;
  thumbnails?:
    | {
        relationTo: 'images';
        value: string | MediaImage;
      }[]
    | null;
  generatorFlags?: (
    | '+auto-generated'
    | '-auto-generated'
    | '+resume-asset'
    | '-resume-asset'
    | '+thumbnail'
    | '-thumbnail'
    | '+document'
    | '-document'
    | '+audio-thumbnail'
    | '-audio-thumbnail'
    | '+video-thumbnail'
    | '-video-thumbnail'
    | '+document-thumbnail'
    | '-document-thumbnail'
  )[];
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audios".
 */
export interface MediaAudio {
  id: string;
  checksum?: string | null;
  generatorFlags?: (
    | '+auto-generated'
    | '-auto-generated'
    | '+resume-asset'
    | '-resume-asset'
    | '+thumbnail'
    | '-thumbnail'
    | '+document'
    | '-document'
    | '+audio-thumbnail'
    | '-audio-thumbnail'
    | '+video-thumbnail'
    | '-video-thumbnail'
    | '+document-thumbnail'
    | '-document-thumbnail'
  )[];
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-customers".
 */
export interface ResumeCustomerData {
  id: string;
  _order?: string | null;
  title: string;
  slug: string;
  svg?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-documents".
 */
export interface ResumeDocumentData {
  id: string;
  title: string;
  slug: string;
  createdAt?: string | null;
  jobId?: (string | null) | PayloadJob;
  checksum_en?: string | null;
  checksum_de?: string | null;
  document_en?: {
    relationTo: 'documents';
    value: string | MediaDocument;
  } | null;
  document_de?: {
    relationTo: 'documents';
    value: string | MediaDocument;
  } | null;
  thumbnails_en?:
    | {
        relationTo: 'images';
        value: string | MediaImage;
      }[]
    | null;
  thumbnails_de?:
    | {
        relationTo: 'images';
        value: string | MediaImage;
      }[]
    | null;
  data_en?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  data_de?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'GenerateDocumentThumbnails'
          | 'CalculateSkillTagInterval'
          | 'GenerateLocalizedResumeDocument'
          | 'createCollectionExport'
          | 'createCollectionImport'
          | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  workflowSlug?: 'GenerateResumeDocument' | null;
  taskSlug?:
    | (
        | 'inline'
        | 'GenerateDocumentThumbnails'
        | 'CalculateSkillTagInterval'
        | 'GenerateLocalizedResumeDocument'
        | 'createCollectionExport'
        | 'createCollectionImport'
        | 'schedulePublish'
      )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-files".
 */
export interface ResumeFileData {
  id: string;
  checksum?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-jobs".
 */
export interface ResumeJobData {
  id: string;
  employer: string;
  title: string;
  tasks?:
    | {
        task: {
          en: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          de: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
        };
        id?: string | null;
      }[]
    | null;
  startDate: string;
  endDate?: string | null;
  interval?: number | null;
  skillTags?:
    | {
        relationTo: 'resume-skill-tags';
        value: string | ResumeSkillTagData;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-skill-tags".
 */
export interface ResumeSkillTagData {
  id: string;
  _order?: string | null;
  title: string;
  slug: string;
  interval?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-projects".
 */
export interface ResumeProjectData {
  id: string;
  scope?: string | null;
  title?: string | null;
  images?:
    | {
        relationTo: 'images';
        value: string | MediaImage;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  published?: boolean | null;
  relatedPost?: {
    relationTo: 'posts';
    value: string | BlogPostData;
  } | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-skills".
 */
export interface ResumeSkillData {
  id: string;
  name: {
    en: string;
    de: string;
  };
  caption?: {
    en?: string | null;
    de?: string | null;
  };
  name_label?: string | null;
  caption_label?: string | null;
  published?: boolean | null;
  type?: SkillType;
  skillTags?:
    | {
        relationTo: 'resume-skill-tags';
        value: string | ResumeSkillTagData;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-exports".
 */
export interface PayloadExport {
  id: string;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-imports".
 */
export interface PayloadImport {
  id: string;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'posts';
        value: string | BlogPostData;
      } | null)
    | ({
        relationTo: 'topics';
        value: string | Topic;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'images';
        value: string | MediaImage;
      } | null)
    | ({
        relationTo: 'videos';
        value: string | MediaVideo;
      } | null)
    | ({
        relationTo: 'documents';
        value: string | MediaDocument;
      } | null)
    | ({
        relationTo: 'audios';
        value: string | MediaAudio;
      } | null)
    | ({
        relationTo: 'resume-customers';
        value: string | ResumeCustomerData;
      } | null)
    | ({
        relationTo: 'resume-documents';
        value: string | ResumeDocumentData;
      } | null)
    | ({
        relationTo: 'resume-files';
        value: string | ResumeFileData;
      } | null)
    | ({
        relationTo: 'resume-jobs';
        value: string | ResumeJobData;
      } | null)
    | ({
        relationTo: 'resume-skill-tags';
        value: string | ResumeSkillTagData;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-query-presets".
 */
export interface PayloadQueryPreset {
  id: string;
  title: string;
  isShared?: boolean | null;
  access?: {
    read?: {
      constraint?: ('everyone' | 'onlyMe' | 'specificUsers') | null;
      users?: (string | User)[] | null;
    };
    update?: {
      constraint?: ('everyone' | 'onlyMe' | 'specificUsers') | null;
      users?: (string | User)[] | null;
    };
    delete?: {
      constraint?: ('everyone' | 'onlyMe' | 'specificUsers') | null;
      users?: (string | User)[] | null;
    };
  };
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  columns?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  groupBy?: string | null;
  relatedCollection: 'images' | 'videos' | 'documents' | 'audios';
  /**
   * This is a temporary field used to determine if updating the preset would remove the user's access to it. When `true`, this record will be deleted after running the preset's `validate` function.
   */
  isTemp?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  topics?: T;
  relatedPosts?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  featured?: T;
  slug?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  protected?: T;
  slug?: T;
  layout?: T;
  hero?:
    | T
    | {
        media?: T;
        contentType?: T;
        content?: T;
      };
  content?: T | {};
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images_select".
 */
export interface ImagesSelect<T extends boolean = true> {
  checksum?: T;
  alt?: T;
  credits?: T;
  blurDataURL?: T;
  generatorFlags?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  checksum?: T;
  caption?: T;
  thumbnails?: T;
  generatorFlags?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  checksum?: T;
  thumbnails?: T;
  generatorFlags?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audios_select".
 */
export interface AudiosSelect<T extends boolean = true> {
  checksum?: T;
  generatorFlags?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-customers_select".
 */
export interface ResumeCustomersSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  svg?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-documents_select".
 */
export interface ResumeDocumentsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  createdAt?: T;
  jobId?: T;
  checksum_en?: T;
  checksum_de?: T;
  document_en?: T;
  document_de?: T;
  thumbnails_en?: T;
  thumbnails_de?: T;
  data_en?: T;
  data_de?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-files_select".
 */
export interface ResumeFilesSelect<T extends boolean = true> {
  checksum?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-jobs_select".
 */
export interface ResumeJobsSelect<T extends boolean = true> {
  employer?: T;
  title?: T;
  tasks?:
    | T
    | {
        task?:
          | T
          | {
              en?: T;
              de?: T;
            };
        id?: T;
      };
  startDate?: T;
  endDate?: T;
  interval?: T;
  skillTags?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-projects_select".
 */
export interface ResumeProjectsSelect<T extends boolean = true> {
  scope?: T;
  title?: T;
  images?: T;
  description?: T;
  published?: T;
  relatedPost?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-skills_select".
 */
export interface ResumeSkillsSelect<T extends boolean = true> {
  name?:
    | T
    | {
        en?: T;
        de?: T;
      };
  caption?:
    | T
    | {
        en?: T;
        de?: T;
      };
  name_label?: T;
  caption_label?: T;
  published?: T;
  type?: T;
  skillTags?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-skill-tags_select".
 */
export interface ResumeSkillTagsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  slug?: T;
  interval?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-exports_select".
 */
export interface PayloadExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-imports_select".
 */
export interface PayloadImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  workflowSlug?: T;
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  concurrencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-query-presets_select".
 */
export interface PayloadQueryPresetsSelect<T extends boolean = true> {
  title?: T;
  isShared?: T;
  access?:
    | T
    | {
        read?:
          | T
          | {
              constraint?: T;
              users?: T;
            };
        update?:
          | T
          | {
              constraint?: T;
              users?: T;
            };
        delete?:
          | T
          | {
              constraint?: T;
              users?: T;
            };
      };
  where?: T;
  columns?: T;
  groupBy?: T;
  relatedCollection?: T;
  isTemp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-site".
 */
export interface SiteSettings {
  id: string;
  general: GeneralSettings;
  header?: HeaderSettings;
  footer?: FooterSettings;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GeneralSettings".
 */
export interface GeneralSettings {
  /**
   * The name of the site.
   */
  siteName?: string | null;
  /**
   * This category is used for generating website metadata.
   */
  category?: string | null;
  /**
   * The host of the site.
   */
  siteHost?: string | null;
  /**
   * The URL of the site.
   */
  siteURL?: string | null;
  /**
   * This template is used for generating the title tag value on each page. Title refers to the actual document title which is suffixed with siteName.
   */
  titleTemplate?: string | null;
  /**
   * This description is used for generating website metadata.  This description is also used as fallback if no document description is available.
   */
  description?: string | null;
  image?: {
    relationTo: 'images';
    value: string | MediaImage;
  } | null;
  errorHero?:
    | (
        | {
            relationTo: 'videos';
            value: string | MediaVideo;
          }
        | {
            relationTo: 'images';
            value: string | MediaImage;
          }
      )[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeaderSettings".
 */
export interface HeaderSettings {
  mainNavigation?: {
    entries?:
      | {
          link: LinkFieldData;
          id?: string | null;
        }[]
      | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterSettings".
 */
export interface FooterSettings {
  column1?: {
    isActive?: boolean | null;
    title?: string | null;
    entries?:
      | {
          link: LinkFieldData;
          id?: string | null;
        }[]
      | null;
  };
  column2?: {
    isActive?: boolean | null;
    title?: string | null;
    entries?:
      | {
          link: LinkFieldData;
          id?: string | null;
        }[]
      | null;
  };
  column3?: {
    isActive?: boolean | null;
    title?: string | null;
    entries?:
      | {
          link: LinkFieldData;
          id?: string | null;
        }[]
      | null;
  };
  legalPages?: {
    entries?:
      | {
          link: LinkFieldData;
          id?: string | null;
        }[]
      | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-pdf-builder".
 */
export interface PDFGeneratorSettings {
  id: string;
  /**
   * The document name template for the documents collection.  
   * The document contains all meta data, file references and the data which was used to generate the PDFs.
   */
  documentTitleTemplate?: string | null;
  /**
   * The filename template for the generated PDF which must satisfy both locales and result in two different filenames.  
   * To get an full overview of all available variables or filter functions use the info icon.
   */
  filenameTemplate?: string | null;
  generateThrottle?: number | null;
  timeoutBetweenJobs?: number | null;
  maximumRetries?: number | null;
  skillSorting?: SkillSorting;
  updatedAt?: string | null;
  createdAt?: string | null;
}
export interface SkillSorting {
  skillTypeSortable: SkillTypeSortable[];
  programmingLanguages: SkillEntrySortable[];
  frameworksAndLibraries: SkillEntrySortable[];
  toolingAndPlatforms: SkillEntrySortable[];
  testingAndQuality: SkillEntrySortable[];
  architectureAndPatterns: SkillEntrySortable[];
  methodologiesAndWorkingPractices: SkillEntrySortable[];
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SkillTypeSortable".
 */
export interface SkillTypeSortable {
  id: SkillType;
  label: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SkillEntrySortable".
 */
export interface SkillEntrySortable {
  id: string;
  label: string;
  caption?: string;
}
/**
 * These user details are stored centrally and used throughout the website wherever the user's profile information is needed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-global-user".
 */
export interface GlobalUserSettings {
  id: string;
  /**
   * Upload your profile picture here.<br />
   * You can choose between a regular and a duotone version.
   */
  portrait?: {
    regular?: {
      relationTo: 'images';
      value: string | MediaImage;
    } | null;
    duotone?: {
      relationTo: 'images';
      value: string | MediaImage;
    } | null;
  };
  url?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  name?: string | null;
  gender?: string | null;
  pronouns?: string | null;
  jobTitle?: string | null;
  homeLocation?: string | null;
  birthPlace?: string | null;
  birthDate?: string | null;
  languages?:
    | {
        language?: LanguageCode;
        proficiency?: LanguageProficiency;
        id?: string | null;
      }[]
    | null;
  taxID?: string | null;
  vatID?: string | null;
  duns?: string | null;
  telephone?: string | null;
  email?: string | null;
  /**
   * This section describes your address information.
   * Those informations are also used on the legal-notice page.
   */
  address?: {
    en?: AddressData;
    de?: AddressData;
  };
  /**
   * This section describes links to your profiles on other platforms, such as social media accounts or personal websites.
   * Those links are also used in the footer of the website in the same order.
   */
  sameAs?:
    | {
        icon?: IconFieldValue;
        name?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * This section describes the organization you work for.
   * It can be used to generate structured data about your employment.
   */
  worksFor?: {
    name?: string | null;
    url?: string | null;
    address?: {
      en?: AddressData;
      de?: AddressData;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AddressData".
 */
export interface AddressData {
  street?: string | null;
  number?: string | null;
  postCode?: string | null;
  place?: string | null;
  countryCode?: string | null;
  countryName?: string | null;
  region?: string | null;
  locality?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  location?: [number, number] | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-site_select".
 */
export interface SettingsSiteSelect<T extends boolean = true> {
  general?: T | GeneralSettingsSelect<T>;
  header?: T | HeaderSettingsSelect<T>;
  footer?: T | FooterSettingsSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GeneralSettings_select".
 */
export interface GeneralSettingsSelect<T extends boolean = true> {
  siteName?: T;
  category?: T;
  siteHost?: T;
  siteURL?: T;
  titleTemplate?: T;
  description?: T;
  image?: T;
  errorHero?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeaderSettings_select".
 */
export interface HeaderSettingsSelect<T extends boolean = true> {
  mainNavigation?:
    | T
    | {
        entries?:
          | T
          | {
              link?: T | LinkFieldDataSelect<T>;
              id?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkFieldData_select".
 */
export interface LinkFieldDataSelect<T extends boolean = true> {
  type?: T;
  newTab?: T;
  icon?: T;
  label?: T;
  iconOnly?: T;
  reference?: T;
  url?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FooterSettings_select".
 */
export interface FooterSettingsSelect<T extends boolean = true> {
  column1?:
    | T
    | {
        isActive?: T;
        title?: T;
        entries?:
          | T
          | {
              link?: T | LinkFieldDataSelect<T>;
              id?: T;
            };
      };
  column2?:
    | T
    | {
        isActive?: T;
        title?: T;
        entries?:
          | T
          | {
              link?: T | LinkFieldDataSelect<T>;
              id?: T;
            };
      };
  column3?:
    | T
    | {
        isActive?: T;
        title?: T;
        entries?:
          | T
          | {
              link?: T | LinkFieldDataSelect<T>;
              id?: T;
            };
      };
  legalPages?:
    | T
    | {
        entries?:
          | T
          | {
              link?: T | LinkFieldDataSelect<T>;
              id?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-pdf-builder_select".
 */
export interface SettingsPdfBuilderSelect<T extends boolean = true> {
  documentTitleTemplate?: T;
  filenameTemplate?: T;
  generateThrottle?: T;
  timeoutBetweenJobs?: T;
  maximumRetries?: T;
  skillSorting?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-global-user_select".
 */
export interface SettingsGlobalUserSelect<T extends boolean = true> {
  portrait?:
    | T
    | {
        regular?: T;
        duotone?: T;
      };
  url?: T;
  firstName?: T;
  lastName?: T;
  name?: T;
  gender?: T;
  pronouns?: T;
  jobTitle?: T;
  homeLocation?: T;
  birthPlace?: T;
  birthDate?: T;
  languages?:
    | T
    | {
        language?: T;
        proficiency?: T;
        id?: T;
      };
  taxID?: T;
  vatID?: T;
  duns?: T;
  telephone?: T;
  email?: T;
  address?:
    | T
    | {
        en?: T | AddressDataSelect<T>;
        de?: T | AddressDataSelect<T>;
      };
  sameAs?:
    | T
    | {
        icon?: T;
        name?: T;
        url?: T;
        id?: T;
      };
  worksFor?:
    | T
    | {
        name?: T;
        url?: T;
        address?:
          | T
          | {
              en?: T | AddressDataSelect<T>;
              de?: T | AddressDataSelect<T>;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AddressData_select".
 */
export interface AddressDataSelect<T extends boolean = true> {
  street?: T;
  number?: T;
  postCode?: T;
  place?: T;
  countryCode?: T;
  countryName?: T;
  region?: T;
  locality?: T;
  location?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "umami-widget_widget".
 */
export interface UmamiWidgetWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerateDocumentThumbnails".
 */
export interface TaskGenerateDocumentThumbnails {
  input: {
    documentId: string;
    maxThumbnails?: number | null;
  };
  output: {
    thumbnailIDs?: string[] | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCalculateSkillTagInterval".
 */
export interface TaskCalculateSkillTagInterval {
  input: {
    skillTagId: string;
  };
  output: {
    interval?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerateLocalizedResumeDocument".
 */
export interface TaskGenerateLocalizedResumeDocument {
  input: {
    locale: 'en' | 'de';
    sharedId: string;
    filenameTemplate: string;
    createdAt: string;
    documentSlug: string;
  };
  output: {
    resumeFileId: string;
    resumeFileChecksum: string;
    resumeThumbnailIds: string[];
    resumeDocumentData:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | 'posts'
      | 'topics'
      | 'pages'
      | 'users'
      | 'images'
      | 'videos'
      | 'documents'
      | 'audios'
      | 'resume-customers'
      | 'resume-documents'
      | 'resume-files'
      | 'resume-jobs'
      | 'resume-projects'
      | 'resume-skills'
      | 'resume-skill-tags'
      | 'payload-exports'
      | 'payload-imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'posts';
          value: string | BlogPostData;
        } | null)
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowGenerateResumeDocument".
 */
export interface WorkflowGenerateResumeDocument {
  input: {
    documentTitleTemplate: string;
    filenameTemplate: string;
    sharedId: string;
    maximumRetries: number;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}