#!/usr/bin/env node

/**
 *    Materialises .env.local from the active Doppler config.
 *
 *    Next loads .env.local automatically, so once this has run the package
 *    scripts need no `doppler run --` wrapper: `pnpm dev`, `pnpm payload` and
 *    the rest pick the environment up on their own. Re-run it whenever the
 *    Doppler config changes, or after switching configs with
 *    `doppler setup --config <name>`.
 *
 *    The file is gitignored (.gitignore:24, `.env.*`) and deliberately not
 *    generated automatically as a side effect of another script: writing every
 *    secret in the project to disk should be something you asked for.
 *
 *    Usage:
 *      node --run load-env            # write .env.local from the active config
 *      node --run load-env -- --check # report drift, write nothing
 */

import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const target = path.join(projectRoot, '.env.local')
const checkOnly = process.argv.slice(2).includes('--check')

const fail = (message) => {
  console.error(`\n[load-env] ${message}\n`)
  process.exit(1)
}

/**
 *    `doppler secrets download --no-file` prints to stdout and never touches
 *    the filesystem, so nothing is written until this script decides to. The
 *    active project/config comes from doppler.yaml plus any local override
 *    made with `doppler setup`, which is why neither is hardcoded here.
 */
let secrets
try {
  secrets = execFileSync(
    'doppler',
    [
      'secrets',
      'download',
      '--no-file',
      '--format',
      'env',
    ],
    {
      cwd: projectRoot,
      encoding: 'utf8',
      // stderr is inherited so Doppler's own diagnostics (not logged in, no
      // config selected, network failure) reach the terminal unmangled.
      stdio: [
        'ignore',
        'pipe',
        'inherit',
      ],
    },
  )
} catch (error) {
  if (error.code === 'ENOENT') {
    fail('the `doppler` CLI is not on PATH — see https://docs.doppler.com/docs/install-cli')
  }
  fail('`doppler secrets download` failed; the output above should say why.')
}

if (!secrets.trim()) {
  fail('Doppler returned no secrets. Is the right config selected? (`doppler configure`)')
}

let config = 'unknown'
try {
  const raw = execFileSync(
    'doppler',
    [
      'configure',
      '--json',
    ],
    {
      cwd: projectRoot,
      encoding: 'utf8',
      stdio: [
        'ignore',
        'pipe',
        'ignore',
      ],
    },
  )
  const scoped = JSON.parse(raw)[projectRoot] ?? {}
  config = `${scoped['enclave.project'] ?? '?'}/${scoped['enclave.config'] ?? '?'}`
} catch {
  // purely informational — a failure here should not stop the write
}

const header =
  '# Generated by `node --run load-env` — do not edit by hand.\n' +
  `# Source: Doppler ${config}\n` +
  '# Re-run after changing the Doppler config or switching configs.\n'
const contents = `${header}\n${secrets.trimEnd()}\n`

const existing = existsSync(target) ? readFileSync(target, 'utf8') : null

if (checkOnly) {
  if (existing === null) {
    fail('.env.local does not exist. Run `node --run load-env` to create it.')
  }
  if (existing !== contents) {
    fail('.env.local is out of date with Doppler. Run `node --run load-env`.')
  }
  console.log(`[load-env] .env.local matches Doppler ${config}`)
  process.exit(0)
}

if (existing === contents) {
  console.log(`[load-env] .env.local already matches Doppler ${config} — nothing to do`)
  process.exit(0)
}

writeFileSync(target, contents, {
  // owner-only: this file holds every secret the project uses
  mode: 0o600,
})

const count = secrets.trimEnd().split('\n').filter(Boolean).length
console.log(
  `[load-env] wrote .env.local from Doppler ${config} (${count} variables)` +
    `${existing === null ? '' : ' — replaced the previous file'}`,
)
