/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageLayout".
 */
export type PageLayout = ('default' | 'home' | 'resume') | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CustomerLogos".
 */
export type CustomerLogos =
  | {
      logo: string;
      name: string;
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "JobHistory".
 */
export type JobHistory =
  | {
      title: string;
      employer: string;
      startDate: string;
      endDate?: string | null;
      content?:
        | {
            item?: string | null;
            id?: string | null;
          }[]
        | null;
      skills: (string | ResumeSkill)[];
      technologies?: {
        id?: string;
        label?: string;
        [k: string]: unknown;
      }[];
      id?: string | null;
    }[]
  | null;
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectList".
 */
export type ProjectList =
  | {
      preHeading: string;
      heading: string;
      image?: (string | null) | MediaImage;
      content?: {
        root: {
          type: string;
          children: {
            type: any;
            version: number;
            [k: string]: unknown;
          }[];
          direction: ('ltr' | 'rtl') | null;
          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
          indent: number;
          version: number;
        };
        [k: string]: unknown;
      } | null;
      id?: string | null;
    }[]
  | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones = 'Europe/Berlin';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    CodeBlock: CodeBlock;
    LinkGroupBlock: LinkGroupBlock;
    OneColumnContentBlock: OneColumnContentBlock;
    TwoColumnContentBlock: TwoColumnContentBlock;
    ResumeAboutMeBlock: ResumeAboutMeBlock;
    ResumeContactBlock: ResumeContactBlock;
    ResumeCustomersBlock: ResumeCustomersBlock;
    ResumeDownloadsBlock: ResumeDownloadsBlock;
    ResumeExperienceBlock: ResumeExperienceBlock;
    ResumeProjectsBlock: ResumeProjectsBlock;
  };
  collections: {
    'blog-categories': BlogCategory;
    'blog-posts': BlogPost;
    images: MediaImage;
    videos: MediaVideo;
    documents: MediaDocument;
    audios: MediaAudio;
    pages: Page;
    users: User;
    'blog-tags': BlogTag;
    'resume-skills': ResumeSkill;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
    'payload-query-presets': PayloadQueryPreset;
  };
  collectionsJoins: {
    'blog-categories': {
      relatedPosts: 'blog-posts';
    };
  };
  collectionsSelect: {
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    images: ImagesSelect<false> | ImagesSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    audios: AudiosSelect<false> | AudiosSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'blog-tags': BlogTagsSelect<false> | BlogTagsSelect<true>;
    'resume-skills': ResumeSkillsSelect<false> | ResumeSkillsSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
    'payload-query-presets': PayloadQueryPresetsSelect<false> | PayloadQueryPresetsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'de') | ('en' | 'de')[];
  globals: {
    'resume-about-me': ResumeAboutMeGlobalData;
    'resume-contact': ResumeContactGlobalData;
    'resume-customers': ResumeCustomersGlobalData;
    'resume-downloads': ResumeDownloadsGlobalData;
    'resume-experience': ResumeExperienceGlobalData;
    'resume-projects': ResumeProjectsGlobalData;
    'settings-header-navigation': HeaderNavigationData;
    'settings-footer-navigation': FooterNavigationData;
    'settings-site-meta': SiteMetaData;
    'settings-user-meta': UserMetaData;
  };
  globalsSelect: {
    'resume-about-me': ResumeAboutMeSelect<false> | ResumeAboutMeSelect<true>;
    'resume-contact': ResumeContactSelect<false> | ResumeContactSelect<true>;
    'resume-customers': ResumeCustomersSelect<false> | ResumeCustomersSelect<true>;
    'resume-downloads': ResumeDownloadsSelect<false> | ResumeDownloadsSelect<true>;
    'resume-experience': ResumeExperienceSelect<false> | ResumeExperienceSelect<true>;
    'resume-projects': ResumeProjectsSelect<false> | ResumeProjectsSelect<true>;
    'settings-header-navigation': SettingsHeaderNavigationSelect<false> | SettingsHeaderNavigationSelect<true>;
    'settings-footer-navigation': SettingsFooterNavigationSelect<false> | SettingsFooterNavigationSelect<true>;
    'settings-site-meta': SettingsSiteMetaSelect<false> | SettingsSiteMetaSelect<true>;
    'settings-user-meta': SettingsUserMetaSelect<false> | SettingsUserMetaSelect<true>;
  };
  locale: 'en' | 'de';
  widgets: {
    'umami-control-bar': UmamiControlBarWidget;
    'umami-stats-widget': UmamiStatsWidgetWidget;
    'umami-pageviews-widget': UmamiPageviewsWidgetWidget;
    'umami-paths-widget': UmamiPathsWidgetWidget;
    'umami-events-widget': UmamiEventsWidgetWidget;
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      generateDocumentThumbnailTask: TaskGenerateDocumentThumbnailTask;
      generateResumeDocumentTask: TaskGenerateResumeDocumentTask;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'CodeBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkGroupBlock".
 */
export interface LinkGroupBlock {
  links?: {
    entries?:
      | {
          link: LinkFieldData;
          id?: string | null;
        }[]
      | null;
    /**
     * Choose how the links should be aligned.
     */
    alignment?: ('left' | 'right' | 'center' | 'list') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'LinkGroupBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkFieldData".
 */
export interface LinkFieldData {
  type?: ('reference' | 'custom' | 'mailto') | null;
  newTab?: boolean | null;
  icon?:
    | (
        | 'simple-icons:archlinux'
        | 'simple-icons:cloudflare'
        | 'simple-icons:cloudflarepages'
        | 'simple-icons:cloudflareworkers'
        | 'simple-icons:debian'
        | 'simple-icons:docker'
        | 'simple-icons:figma'
        | 'simple-icons:github'
        | 'simple-icons:githubactions'
        | 'simple-icons:githubpages'
        | 'simple-icons:gitlab'
        | 'simple-icons:goland'
        | 'simple-icons:homeassistant'
        | 'simple-icons:intellijidea'
        | 'simple-icons:javascript'
        | 'simple-icons:jetbrains'
        | 'simple-icons:kubernetes'
        | 'simple-icons:linkedin'
        | 'simple-icons:linux'
        | 'simple-icons:maildotru'
        | 'simple-icons:namecheap'
        | 'simple-icons:nextdotjs'
        | 'simple-icons:nodedotjs'
        | 'simple-icons:1password'
        | 'simple-icons:payloadcms'
        | 'simple-icons:phpstorm'
        | 'simple-icons:pycharm'
        | 'simple-icons:rancher'
        | 'simple-icons:react'
        | 'simple-icons:rust'
        | 'simple-icons:sanity'
        | 'simple-icons:storybook'
        | 'simple-icons:synology'
        | 'simple-icons:tailscale'
        | 'simple-icons:ubuntu'
        | 'simple-icons:unsplash'
        | 'simple-icons:vercel'
        | 'simple-icons:webstorm'
        | 'simple-icons:whatsapp'
        | 'simple-icons:wireguard'
        | 'simple-icons:xing'
        | 'simple-icons:zigbee'
        | 'material-symbols:contextual-token-outline-sharp'
        | 'material-symbols:post-outline'
        | 'material-symbols:label-outline-sharp'
        | 'material-symbols:contact-page-outline-sharp'
        | 'material-symbols:video-file-outline-sharp'
        | 'material-symbols:audio-file-outline-sharp'
        | 'material-symbols:picture-as-pdf-outline-sharp'
        | 'material-symbols:pages-outline-sharp'
        | 'material-symbols:fingerprint-sharp'
        | 'material-symbols:stacked-email-outline-sharp'
        | 'material-symbols:deployed-code-account-outline-sharp'
        | 'material-symbols:work-outline-sharp'
        | 'material-symbols:experiment-outline-sharp'
        | 'material-symbols:page-footer-outline-sharp'
        | 'material-symbols:page-header-outline-sharp'
        | 'material-symbols:map-search-outline-sharp'
        | 'material-symbols:settings-account-box-sharp'
        | 'material-symbols:account-box-outline-sharp'
        | 'material-symbols:error'
        | 'material-symbols:warning'
        | 'material-symbols:info'
        | 'material-symbols:check-circle'
        | 'material-symbols:call'
        | 'material-symbols:pause'
        | 'material-symbols:play-arrow'
        | 'material-symbols:stop'
        | 'material-symbols:repeat'
        | 'material-symbols:replay'
        | 'material-symbols:attach-file'
        | 'material-symbols:settings'
        | 'material-symbols:calendar-month'
        | 'material-symbols:keyboard-arrow-down'
        | 'material-symbols:keyboard-arrow-up'
        | 'material-symbols:keyboard-arrow-left'
        | 'material-symbols:keyboard-arrow-right'
        | 'material-symbols:trending-up'
        | 'material-symbols:trending-down'
        | 'material-symbols:trending-flat'
        | 'material-symbols:touch-app'
        | 'material-symbols:person'
        | 'material-symbols:group'
        | 'material-symbols:web-traffic'
        | 'material-symbols:highlight-mouse-cursor'
        | 'material-symbols:undo'
        | 'material-symbols:nest-clock-farsight-analog-outline'
        | 'material-symbols:multimodal-hand-eye'
        | 'material-symbols:close'
        | 'material-symbols:image-outline-sharp'
        | 'material-symbols:logout-sharp'
      )
    | null;
  label: string;
  iconOnly?: boolean | null;
  reference?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: string | BlogPost;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: string | BlogCategory;
      } | null)
    | ({
        relationTo: 'blog-tags';
        value: string | BlogTag;
      } | null);
  url?: string | null;
  address?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug?: string | null;
  layout?: PageLayout;
  hero?: {
    media?: (string | MediaImage)[] | null;
    contentType?: ('title' | 'custom') | null;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  content?:
    | (
        | CodeBlock
        | LinkGroupBlock
        | OneColumnContentBlock
        | TwoColumnContentBlock
        | ResumeAboutMeBlock
        | ResumeContactBlock
        | ResumeCustomersBlock
        | ResumeDownloadsBlock
        | ResumeExperienceBlock
        | ResumeProjectsBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images".
 */
export interface MediaImage {
  id: string;
  alt?: string | null;
  credits?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  blurDataURL?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OneColumnContentBlock".
 */
export interface OneColumnContentBlock {
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'OneColumnContentBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TwoColumnContentBlock".
 */
export interface TwoColumnContentBlock {
  contentLeft?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contentRight?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'TwoColumnContentBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResumeAboutMeBlock".
 */
export interface ResumeAboutMeBlock {
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ResumeAboutMeBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResumeContactBlock".
 */
export interface ResumeContactBlock {
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ResumeContactBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResumeCustomersBlock".
 */
export interface ResumeCustomersBlock {
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ResumeCustomersBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResumeDownloadsBlock".
 */
export interface ResumeDownloadsBlock {
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ResumeDownloadsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResumeExperienceBlock".
 */
export interface ResumeExperienceBlock {
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ResumeExperienceBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ResumeProjectsBlock".
 */
export interface ResumeProjectsBlock {
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ResumeProjectsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: string;
  title: string;
  slug?: string | null;
  heroImage?: (string | null) | MediaImage;
  categories?: (string | null) | BlogCategory;
  tags?: (string | BlogTag)[] | null;
  relatedPosts?: (string | BlogPost)[] | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: string;
  title: string;
  slug?: string | null;
  heroImage?: (string | null) | MediaImage;
  parent?: (string | null) | BlogCategory;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  breadcrumbs?:
    | {
        doc?: (string | null) | BlogCategory;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  breadcrumbsPath?: string | null;
  relatedPosts?: {
    docs?: (string | BlogPost)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-tags".
 */
export interface BlogTag {
  id: string;
  title: string;
  slug?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface MediaVideo {
  id: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface MediaDocument {
  id: string;
  thumbnail?: (string | null) | MediaImage;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audios".
 */
export interface MediaAudio {
  id: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  avatar?: (string | null) | MediaImage;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-skills".
 */
export interface ResumeSkill {
  id: string;
  name: string;
  slug?: string | null;
  type?: ('technology' | 'programmingLanguage' | 'methodology' | 'language' | 'privateInterest') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'generateDocumentThumbnailTask' | 'generateResumeDocumentTask' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'generateDocumentThumbnailTask' | 'generateResumeDocumentTask' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'blog-categories';
        value: string | BlogCategory;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: string | BlogPost;
      } | null)
    | ({
        relationTo: 'images';
        value: string | MediaImage;
      } | null)
    | ({
        relationTo: 'videos';
        value: string | MediaVideo;
      } | null)
    | ({
        relationTo: 'documents';
        value: string | MediaDocument;
      } | null)
    | ({
        relationTo: 'audios';
        value: string | MediaAudio;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'blog-tags';
        value: string | BlogTag;
      } | null)
    | ({
        relationTo: 'resume-skills';
        value: string | ResumeSkill;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-query-presets".
 */
export interface PayloadQueryPreset {
  id: string;
  title: string;
  isShared?: boolean | null;
  access?: {
    read?: {
      constraint?: ('everyone' | 'onlyMe' | 'specificUsers') | null;
      users?: (string | User)[] | null;
    };
    update?: {
      constraint?: ('everyone' | 'onlyMe' | 'specificUsers') | null;
      users?: (string | User)[] | null;
    };
    delete?: {
      constraint?: ('everyone' | 'onlyMe' | 'specificUsers') | null;
      users?: (string | User)[] | null;
    };
  };
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  columns?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  groupBy?: string | null;
  relatedCollection: 'documents';
  /**
   * This is a temporary field used to determine if updating the preset would remove the user's access to it. When `true`, this record will be deleted after running the preset's `validate` function.
   */
  isTemp?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  parent?: T;
  content?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  breadcrumbsPath?: T;
  relatedPosts?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  heroImage?: T;
  categories?: T;
  tags?: T;
  relatedPosts?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "images_select".
 */
export interface ImagesSelect<T extends boolean = true> {
  alt?: T;
  credits?: T;
  blurDataURL?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  thumbnail?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audios_select".
 */
export interface AudiosSelect<T extends boolean = true> {
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?: T;
  hero?:
    | T
    | {
        media?: T;
        contentType?: T;
        content?: T;
      };
  content?: T | {};
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-tags_select".
 */
export interface BlogTagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-skills_select".
 */
export interface ResumeSkillsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  concurrencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-query-presets_select".
 */
export interface PayloadQueryPresetsSelect<T extends boolean = true> {
  title?: T;
  isShared?: T;
  access?:
    | T
    | {
        read?:
          | T
          | {
              constraint?: T;
              users?: T;
            };
        update?:
          | T
          | {
              constraint?: T;
              users?: T;
            };
        delete?:
          | T
          | {
              constraint?: T;
              users?: T;
            };
      };
  where?: T;
  columns?: T;
  groupBy?: T;
  relatedCollection?: T;
  isTemp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-about-me".
 */
export interface ResumeAboutMeGlobalData {
  id: string;
  title: string;
  portrait?: (string | null) | MediaImage;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-contact".
 */
export interface ResumeContactGlobalData {
  id: string;
  title: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-customers".
 */
export interface ResumeCustomersGlobalData {
  id: string;
  title: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  customerLogos?: CustomerLogos;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-downloads".
 */
export interface ResumeDownloadsGlobalData {
  id: string;
  title: string;
  documents?: {
    en?: (string | null) | MediaDocument;
    de?: (string | null) | MediaDocument;
  };
  documentPreview?: (string | null) | MediaImage;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-experience".
 */
export interface ResumeExperienceGlobalData {
  id: string;
  title: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  jobHistory?: JobHistory;
  skillSummary?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[A-Za-z0-9_-]+$".
     */
    [k: string]: {
      label: string;
      time: number;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-projects".
 */
export interface ResumeProjectsGlobalData {
  id: string;
  title: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  projectList?: ProjectList;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-header-navigation".
 */
export interface HeaderNavigationData {
  id: string;
  mainNavigation?:
    | {
        link: LinkFieldData;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-footer-navigation".
 */
export interface FooterNavigationData {
  id: string;
  navGroups?:
    | {
        title?: string | null;
        entries?:
          | {
              link: LinkFieldData;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?: {
    title?: string | null;
    entries?:
      | {
          link: LinkFieldData;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-site-meta".
 */
export interface SiteMetaData {
  id: string;
  siteName?: string | null;
  /**
   * This template is used for generating the title tag value on each page. Title refers to the actual document title which is suffixed with siteName.
   */
  titleTemplate?: string | null;
  /**
   * This URL is used for generating website metadata.
   */
  siteUrl?: string | null;
  /**
   * This category is used for generating website metadata.
   */
  category?: string | null;
  /**
   * This description is used for generating website metadata.This description is also used as fallback if no document description is available.
   */
  description?: string | null;
  image?: (string | null) | MediaImage;
  keywords?: {
    id?: string;
    label?: string;
    [k: string]: unknown;
  }[];
  /**
   * This URL is used for generating website metadata.
   */
  searchUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-user-meta".
 */
export interface UserMetaData {
  id: string;
  image?: (string | null) | MediaImage;
  url?: string | null;
  name?: string | null;
  jobTitle?: string | null;
  gender?: string | null;
  homeLocation?: string | null;
  birthPlace?: string | null;
  birthDate?: string | null;
  languages?:
    | {
        language?:
          | (
              | 'aa'
              | 'ab'
              | 'ae'
              | 'af'
              | 'ak'
              | 'am'
              | 'an'
              | 'ar'
              | 'as'
              | 'av'
              | 'ay'
              | 'az'
              | 'ba'
              | 'be'
              | 'bg'
              | 'bi'
              | 'bm'
              | 'bn'
              | 'bo'
              | 'br'
              | 'bs'
              | 'ca'
              | 'ce'
              | 'ch'
              | 'co'
              | 'cr'
              | 'cs'
              | 'cu'
              | 'cv'
              | 'cy'
              | 'da'
              | 'de'
              | 'dv'
              | 'dz'
              | 'ee'
              | 'el'
              | 'en'
              | 'eo'
              | 'es'
              | 'et'
              | 'eu'
              | 'fa'
              | 'ff'
              | 'fi'
              | 'fj'
              | 'fo'
              | 'fr'
              | 'fy'
              | 'ga'
              | 'gd'
              | 'gl'
              | 'gn'
              | 'gu'
              | 'gv'
              | 'ha'
              | 'he'
              | 'hi'
              | 'ho'
              | 'hr'
              | 'ht'
              | 'hu'
              | 'hy'
              | 'hz'
              | 'ia'
              | 'id'
              | 'ie'
              | 'ig'
              | 'ii'
              | 'ik'
              | 'io'
              | 'is'
              | 'it'
              | 'iu'
              | 'ja'
              | 'jv'
              | 'ka'
              | 'kg'
              | 'ki'
              | 'kj'
              | 'kk'
              | 'kl'
              | 'km'
              | 'kn'
              | 'ko'
              | 'kr'
              | 'ks'
              | 'ku'
              | 'kv'
              | 'kw'
              | 'ky'
              | 'la'
              | 'lb'
              | 'lg'
              | 'li'
              | 'ln'
              | 'lo'
              | 'lt'
              | 'lu'
              | 'lv'
              | 'mg'
              | 'mh'
              | 'mi'
              | 'mk'
              | 'ml'
              | 'mn'
              | 'mr'
              | 'ms'
              | 'mt'
              | 'my'
              | 'na'
              | 'nb'
              | 'nd'
              | 'ne'
              | 'ng'
              | 'nl'
              | 'nn'
              | 'no'
              | 'nr'
              | 'nv'
              | 'ny'
              | 'oc'
              | 'oj'
              | 'om'
              | 'or'
              | 'os'
              | 'pa'
              | 'pi'
              | 'pl'
              | 'ps'
              | 'pt'
              | 'qu'
              | 'rm'
              | 'rn'
              | 'ro'
              | 'ru'
              | 'rw'
              | 'sa'
              | 'sc'
              | 'sd'
              | 'se'
              | 'sg'
              | 'si'
              | 'sk'
              | 'sl'
              | 'sm'
              | 'sn'
              | 'so'
              | 'sq'
              | 'sr'
              | 'ss'
              | 'st'
              | 'su'
              | 'sv'
              | 'sw'
              | 'ta'
              | 'te'
              | 'tg'
              | 'th'
              | 'ti'
              | 'tk'
              | 'tl'
              | 'tn'
              | 'to'
              | 'tr'
              | 'ts'
              | 'tt'
              | 'tw'
              | 'ty'
              | 'ug'
              | 'uk'
              | 'ur'
              | 'uz'
              | 've'
              | 'vi'
              | 'vo'
              | 'wa'
              | 'wo'
              | 'xh'
              | 'yi'
              | 'yo'
              | 'za'
              | 'zh'
              | 'zu'
            )
          | null;
        proficiency?: ('A1' | 'A2' | 'B1' | 'B2' | 'C1' | 'C2') | null;
        id?: string | null;
      }[]
    | null;
  taxID?: string | null;
  vatID?: string | null;
  duns?: string | null;
  telephone?: string | null;
  email?: string | null;
  /**
   * This section describes links to your profiles on other platforms, such as social media accounts or personal websites.
   */
  sameAs?:
    | {
        icon?:
          | (
              | 'simple-icons:archlinux'
              | 'simple-icons:cloudflare'
              | 'simple-icons:cloudflarepages'
              | 'simple-icons:cloudflareworkers'
              | 'simple-icons:debian'
              | 'simple-icons:docker'
              | 'simple-icons:figma'
              | 'simple-icons:github'
              | 'simple-icons:githubactions'
              | 'simple-icons:githubpages'
              | 'simple-icons:gitlab'
              | 'simple-icons:goland'
              | 'simple-icons:homeassistant'
              | 'simple-icons:intellijidea'
              | 'simple-icons:javascript'
              | 'simple-icons:jetbrains'
              | 'simple-icons:kubernetes'
              | 'simple-icons:linkedin'
              | 'simple-icons:linux'
              | 'simple-icons:maildotru'
              | 'simple-icons:namecheap'
              | 'simple-icons:nextdotjs'
              | 'simple-icons:nodedotjs'
              | 'simple-icons:1password'
              | 'simple-icons:payloadcms'
              | 'simple-icons:phpstorm'
              | 'simple-icons:pycharm'
              | 'simple-icons:rancher'
              | 'simple-icons:react'
              | 'simple-icons:rust'
              | 'simple-icons:sanity'
              | 'simple-icons:storybook'
              | 'simple-icons:synology'
              | 'simple-icons:tailscale'
              | 'simple-icons:ubuntu'
              | 'simple-icons:unsplash'
              | 'simple-icons:vercel'
              | 'simple-icons:webstorm'
              | 'simple-icons:whatsapp'
              | 'simple-icons:wireguard'
              | 'simple-icons:xing'
              | 'simple-icons:zigbee'
              | 'material-symbols:contextual-token-outline-sharp'
              | 'material-symbols:post-outline'
              | 'material-symbols:label-outline-sharp'
              | 'material-symbols:contact-page-outline-sharp'
              | 'material-symbols:video-file-outline-sharp'
              | 'material-symbols:audio-file-outline-sharp'
              | 'material-symbols:picture-as-pdf-outline-sharp'
              | 'material-symbols:pages-outline-sharp'
              | 'material-symbols:fingerprint-sharp'
              | 'material-symbols:stacked-email-outline-sharp'
              | 'material-symbols:deployed-code-account-outline-sharp'
              | 'material-symbols:work-outline-sharp'
              | 'material-symbols:experiment-outline-sharp'
              | 'material-symbols:page-footer-outline-sharp'
              | 'material-symbols:page-header-outline-sharp'
              | 'material-symbols:map-search-outline-sharp'
              | 'material-symbols:settings-account-box-sharp'
              | 'material-symbols:account-box-outline-sharp'
              | 'material-symbols:error'
              | 'material-symbols:warning'
              | 'material-symbols:info'
              | 'material-symbols:check-circle'
              | 'material-symbols:call'
              | 'material-symbols:pause'
              | 'material-symbols:play-arrow'
              | 'material-symbols:stop'
              | 'material-symbols:repeat'
              | 'material-symbols:replay'
              | 'material-symbols:attach-file'
              | 'material-symbols:settings'
              | 'material-symbols:calendar-month'
              | 'material-symbols:keyboard-arrow-down'
              | 'material-symbols:keyboard-arrow-up'
              | 'material-symbols:keyboard-arrow-left'
              | 'material-symbols:keyboard-arrow-right'
              | 'material-symbols:trending-up'
              | 'material-symbols:trending-down'
              | 'material-symbols:trending-flat'
              | 'material-symbols:touch-app'
              | 'material-symbols:person'
              | 'material-symbols:group'
              | 'material-symbols:web-traffic'
              | 'material-symbols:highlight-mouse-cursor'
              | 'material-symbols:undo'
              | 'material-symbols:nest-clock-farsight-analog-outline'
              | 'material-symbols:multimodal-hand-eye'
              | 'material-symbols:close'
              | 'material-symbols:image-outline-sharp'
              | 'material-symbols:logout-sharp'
            )
          | null;
        name?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  /**
   * This section describes the organization you work for.
   * It can be used to generate structured data about your employment.
   */
  worksFor?: {
    name?: string | null;
    url?: string | null;
    address?: AddressData;
  };
  address?: AddressData;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AddressData".
 */
export interface AddressData {
  street?: string | null;
  number?: string | null;
  postCode?: string | null;
  place?: string | null;
  countryCode?: string | null;
  countryName?: string | null;
  region?: string | null;
  locality?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  location?: [number, number] | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-about-me_select".
 */
export interface ResumeAboutMeSelect<T extends boolean = true> {
  title?: T;
  portrait?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-contact_select".
 */
export interface ResumeContactSelect<T extends boolean = true> {
  title?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-customers_select".
 */
export interface ResumeCustomersSelect<T extends boolean = true> {
  title?: T;
  caption?: T;
  customerLogos?: T | CustomerLogosSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CustomerLogos_select".
 */
export interface CustomerLogosSelect<T extends boolean = true> {
  logo?: T;
  name?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-downloads_select".
 */
export interface ResumeDownloadsSelect<T extends boolean = true> {
  title?: T;
  documents?:
    | T
    | {
        en?: T;
        de?: T;
      };
  documentPreview?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-experience_select".
 */
export interface ResumeExperienceSelect<T extends boolean = true> {
  title?: T;
  caption?: T;
  jobHistory?: T | JobHistorySelect<T>;
  skillSummary?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "JobHistory_select".
 */
export interface JobHistorySelect<T extends boolean = true> {
  title?: T;
  employer?: T;
  startDate?: T;
  endDate?: T;
  content?:
    | T
    | {
        item?: T;
        id?: T;
      };
  skills?: T;
  technologies?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resume-projects_select".
 */
export interface ResumeProjectsSelect<T extends boolean = true> {
  title?: T;
  caption?: T;
  projectList?: T | ProjectListSelect<T>;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectList_select".
 */
export interface ProjectListSelect<T extends boolean = true> {
  preHeading?: T;
  heading?: T;
  image?: T;
  content?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-header-navigation_select".
 */
export interface SettingsHeaderNavigationSelect<T extends boolean = true> {
  mainNavigation?:
    | T
    | {
        link?: T | LinkFieldDataSelect<T>;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkFieldData_select".
 */
export interface LinkFieldDataSelect<T extends boolean = true> {
  type?: T;
  newTab?: T;
  icon?: T;
  label?: T;
  iconOnly?: T;
  reference?: T;
  url?: T;
  address?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-footer-navigation_select".
 */
export interface SettingsFooterNavigationSelect<T extends boolean = true> {
  navGroups?:
    | T
    | {
        title?: T;
        entries?:
          | T
          | {
              link?: T | LinkFieldDataSelect<T>;
              id?: T;
            };
        id?: T;
      };
  legalLinks?:
    | T
    | {
        title?: T;
        entries?:
          | T
          | {
              link?: T | LinkFieldDataSelect<T>;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-site-meta_select".
 */
export interface SettingsSiteMetaSelect<T extends boolean = true> {
  siteName?: T;
  titleTemplate?: T;
  siteUrl?: T;
  category?: T;
  description?: T;
  image?: T;
  keywords?: T;
  searchUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings-user-meta_select".
 */
export interface SettingsUserMetaSelect<T extends boolean = true> {
  image?: T;
  url?: T;
  name?: T;
  jobTitle?: T;
  gender?: T;
  homeLocation?: T;
  birthPlace?: T;
  birthDate?: T;
  languages?:
    | T
    | {
        language?: T;
        proficiency?: T;
        id?: T;
      };
  taxID?: T;
  vatID?: T;
  duns?: T;
  telephone?: T;
  email?: T;
  sameAs?:
    | T
    | {
        icon?: T;
        name?: T;
        url?: T;
        id?: T;
      };
  description?: T;
  worksFor?:
    | T
    | {
        name?: T;
        url?: T;
        address?: T | AddressDataSelect<T>;
      };
  address?: T | AddressDataSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "AddressData_select".
 */
export interface AddressDataSelect<T extends boolean = true> {
  street?: T;
  number?: T;
  postCode?: T;
  place?: T;
  countryCode?: T;
  countryName?: T;
  region?: T;
  locality?: T;
  location?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "umami-control-bar_widget".
 */
export interface UmamiControlBarWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "umami-stats-widget_widget".
 */
export interface UmamiStatsWidgetWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "umami-pageviews-widget_widget".
 */
export interface UmamiPageviewsWidgetWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'medium' | 'large' | 'x-large' | 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "umami-paths-widget_widget".
 */
export interface UmamiPathsWidgetWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'x-small' | 'small' | 'medium';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "umami-events-widget_widget".
 */
export interface UmamiEventsWidgetWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'x-small' | 'small' | 'medium';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerateDocumentThumbnailTask".
 */
export interface TaskGenerateDocumentThumbnailTask {
  input: {
    documentId: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerateResumeDocumentTask".
 */
export interface TaskGenerateResumeDocumentTask {
  input: {
    locale: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'blog-posts';
          value: string | BlogPost;
        } | null)
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}